// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/minikms/v1/audit.proto

package minikmsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type AuditEntry struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	PreviousHash   string                 `protobuf:"bytes,2,opt,name=previous_hash,json=previousHash,proto3" json:"previous_hash,omitempty"`
	EntryHash      string                 `protobuf:"bytes,3,opt,name=entry_hash,json=entryHash,proto3" json:"entry_hash,omitempty"`
	Timestamp      string                 `protobuf:"bytes,4,opt,name=timestamp,proto3" json:"timestamp,omitempty"` // RFC3339Nano
	Action         string                 `protobuf:"bytes,5,opt,name=action,proto3" json:"action,omitempty"`
	ActorId        string                 `protobuf:"bytes,6,opt,name=actor_id,json=actorId,proto3" json:"actor_id,omitempty"`
	OrgId          string                 `protobuf:"bytes,7,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Details        string                 `protobuf:"bytes,8,opt,name=details,proto3" json:"details,omitempty"`
	RequestJwtHash string                 `protobuf:"bytes,9,opt,name=request_jwt_hash,json=requestJwtHash,proto3" json:"request_jwt_hash,omitempty"` // SHA-256 of JWT used for this request
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *AuditEntry) Reset() {
	*x = AuditEntry{}
	mi := &file_api_proto_minikms_v1_audit_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AuditEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AuditEntry) ProtoMessage() {}

func (x *AuditEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_audit_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AuditEntry.ProtoReflect.Descriptor instead.
func (*AuditEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_audit_proto_rawDescGZIP(), []int{0}
}

func (x *AuditEntry) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *AuditEntry) GetPreviousHash() string {
	if x != nil {
		return x.PreviousHash
	}
	return ""
}

func (x *AuditEntry) GetEntryHash() string {
	if x != nil {
		return x.EntryHash
	}
	return ""
}

func (x *AuditEntry) GetTimestamp() string {
	if x != nil {
		return x.Timestamp
	}
	return ""
}

func (x *AuditEntry) GetAction() string {
	if x != nil {
		return x.Action
	}
	return ""
}

func (x *AuditEntry) GetActorId() string {
	if x != nil {
		return x.ActorId
	}
	return ""
}

func (x *AuditEntry) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *AuditEntry) GetDetails() string {
	if x != nil {
		return x.Details
	}
	return ""
}

func (x *AuditEntry) GetRequestJwtHash() string {
	if x != nil {
		return x.RequestJwtHash
	}
	return ""
}

type GetAuditLogsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Limit         int32                  `protobuf:"varint,2,opt,name=limit,proto3" json:"limit,omitempty"`
	Offset        int32                  `protobuf:"varint,3,opt,name=offset,proto3" json:"offset,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogsRequest) Reset() {
	*x = GetAuditLogsRequest{}
	mi := &file_api_proto_minikms_v1_audit_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogsRequest) ProtoMessage() {}

func (x *GetAuditLogsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_audit_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogsRequest.ProtoReflect.Descriptor instead.
func (*GetAuditLogsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_audit_proto_rawDescGZIP(), []int{1}
}

func (x *GetAuditLogsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *GetAuditLogsRequest) GetLimit() int32 {
	if x != nil {
		return x.Limit
	}
	return 0
}

func (x *GetAuditLogsRequest) GetOffset() int32 {
	if x != nil {
		return x.Offset
	}
	return 0
}

type GetAuditLogsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*AuditEntry          `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetAuditLogsResponse) Reset() {
	*x = GetAuditLogsResponse{}
	mi := &file_api_proto_minikms_v1_audit_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAuditLogsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAuditLogsResponse) ProtoMessage() {}

func (x *GetAuditLogsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_audit_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAuditLogsResponse.ProtoReflect.Descriptor instead.
func (*GetAuditLogsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_audit_proto_rawDescGZIP(), []int{2}
}

func (x *GetAuditLogsResponse) GetEntries() []*AuditEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type VerifyChainRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyChainRequest) Reset() {
	*x = VerifyChainRequest{}
	mi := &file_api_proto_minikms_v1_audit_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyChainRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyChainRequest) ProtoMessage() {}

func (x *VerifyChainRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_audit_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyChainRequest.ProtoReflect.Descriptor instead.
func (*VerifyChainRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_audit_proto_rawDescGZIP(), []int{3}
}

func (x *VerifyChainRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type VerifyChainResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VerifyChainResponse) Reset() {
	*x = VerifyChainResponse{}
	mi := &file_api_proto_minikms_v1_audit_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VerifyChainResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VerifyChainResponse) ProtoMessage() {}

func (x *VerifyChainResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_audit_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VerifyChainResponse.ProtoReflect.Descriptor instead.
func (*VerifyChainResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_audit_proto_rawDescGZIP(), []int{4}
}

func (x *VerifyChainResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

var File_api_proto_minikms_v1_audit_proto protoreflect.FileDescriptor

const file_api_proto_minikms_v1_audit_proto_rawDesc = "" +
	"\n" +
	" api/proto/minikms/v1/audit.proto\x12\n" +
	"minikms.v1\"\x8c\x02\n" +
	"\n" +
	"AuditEntry\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12#\n" +
	"\rprevious_hash\x18\x02 \x01(\tR\fpreviousHash\x12\x1d\n" +
	"\n" +
	"entry_hash\x18\x03 \x01(\tR\tentryHash\x12\x1c\n" +
	"\ttimestamp\x18\x04 \x01(\tR\ttimestamp\x12\x16\n" +
	"\x06action\x18\x05 \x01(\tR\x06action\x12\x19\n" +
	"\bactor_id\x18\x06 \x01(\tR\aactorId\x12\x15\n" +
	"\x06org_id\x18\a \x01(\tR\x05orgId\x12\x18\n" +
	"\adetails\x18\b \x01(\tR\adetails\x12(\n" +
	"\x10request_jwt_hash\x18\t \x01(\tR\x0erequestJwtHash\"Z\n" +
	"\x13GetAuditLogsRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x14\n" +
	"\x05limit\x18\x02 \x01(\x05R\x05limit\x12\x16\n" +
	"\x06offset\x18\x03 \x01(\x05R\x06offset\"H\n" +
	"\x14GetAuditLogsResponse\x120\n" +
	"\aentries\x18\x01 \x03(\v2\x16.minikms.v1.AuditEntryR\aentries\"+\n" +
	"\x12VerifyChainRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\"+\n" +
	"\x13VerifyChainResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid2\xb1\x01\n" +
	"\fAuditService\x12Q\n" +
	"\fGetAuditLogs\x12\x1f.minikms.v1.GetAuditLogsRequest\x1a .minikms.v1.GetAuditLogsResponse\x12N\n" +
	"\vVerifyChain\x12\x1e.minikms.v1.VerifyChainRequest\x1a\x1f.minikms.v1.VerifyChainResponseB;Z9github.com/envsync/minikms/api/proto/minikms/v1;minikmsv1b\x06proto3"

var (
	file_api_proto_minikms_v1_audit_proto_rawDescOnce sync.Once
	file_api_proto_minikms_v1_audit_proto_rawDescData []byte
)

func file_api_proto_minikms_v1_audit_proto_rawDescGZIP() []byte {
	file_api_proto_minikms_v1_audit_proto_rawDescOnce.Do(func() {
		file_api_proto_minikms_v1_audit_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_minikms_v1_audit_proto_rawDesc), len(file_api_proto_minikms_v1_audit_proto_rawDesc)))
	})
	return file_api_proto_minikms_v1_audit_proto_rawDescData
}

var file_api_proto_minikms_v1_audit_proto_msgTypes = make([]protoimpl.MessageInfo, 5)
var file_api_proto_minikms_v1_audit_proto_goTypes = []any{
	(*AuditEntry)(nil),           // 0: minikms.v1.AuditEntry
	(*GetAuditLogsRequest)(nil),  // 1: minikms.v1.GetAuditLogsRequest
	(*GetAuditLogsResponse)(nil), // 2: minikms.v1.GetAuditLogsResponse
	(*VerifyChainRequest)(nil),   // 3: minikms.v1.VerifyChainRequest
	(*VerifyChainResponse)(nil),  // 4: minikms.v1.VerifyChainResponse
}
var file_api_proto_minikms_v1_audit_proto_depIdxs = []int32{
	0, // 0: minikms.v1.GetAuditLogsResponse.entries:type_name -> minikms.v1.AuditEntry
	1, // 1: minikms.v1.AuditService.GetAuditLogs:input_type -> minikms.v1.GetAuditLogsRequest
	3, // 2: minikms.v1.AuditService.VerifyChain:input_type -> minikms.v1.VerifyChainRequest
	2, // 3: minikms.v1.AuditService.GetAuditLogs:output_type -> minikms.v1.GetAuditLogsResponse
	4, // 4: minikms.v1.AuditService.VerifyChain:output_type -> minikms.v1.VerifyChainResponse
	3, // [3:5] is the sub-list for method output_type
	1, // [1:3] is the sub-list for method input_type
	1, // [1:1] is the sub-list for extension type_name
	1, // [1:1] is the sub-list for extension extendee
	0, // [0:1] is the sub-list for field type_name
}

func init() { file_api_proto_minikms_v1_audit_proto_init() }
func file_api_proto_minikms_v1_audit_proto_init() {
	if File_api_proto_minikms_v1_audit_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_minikms_v1_audit_proto_rawDesc), len(file_api_proto_minikms_v1_audit_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   5,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_minikms_v1_audit_proto_goTypes,
		DependencyIndexes: file_api_proto_minikms_v1_audit_proto_depIdxs,
		MessageInfos:      file_api_proto_minikms_v1_audit_proto_msgTypes,
	}.Build()
	File_api_proto_minikms_v1_audit_proto = out.File
	file_api_proto_minikms_v1_audit_proto_goTypes = nil
	file_api_proto_minikms_v1_audit_proto_depIdxs = nil
}
