// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/minikms/v1/kms.proto

package minikmsv1

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type EncryptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"` // Tenant identifier (maps to org_id in EnvSync)
	ScopeId       string                 `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`    // Scope/namespace identifier (maps to app_id in EnvSync)
	Plaintext     []byte                 `protobuf:"bytes,3,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	Aad           string                 `protobuf:"bytes,4,opt,name=aad,proto3" json:"aad,omitempty"` // Additional Authenticated Data for context binding
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptRequest) Reset() {
	*x = EncryptRequest{}
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptRequest) ProtoMessage() {}

func (x *EncryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptRequest.ProtoReflect.Descriptor instead.
func (*EncryptRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_kms_proto_rawDescGZIP(), []int{0}
}

func (x *EncryptRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *EncryptRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *EncryptRequest) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *EncryptRequest) GetAad() string {
	if x != nil {
		return x.Aad
	}
	return ""
}

type EncryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    string                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"` // base64-encoded
	KeyVersionId  string                 `protobuf:"bytes,2,opt,name=key_version_id,json=keyVersionId,proto3" json:"key_version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *EncryptResponse) Reset() {
	*x = EncryptResponse{}
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *EncryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*EncryptResponse) ProtoMessage() {}

func (x *EncryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use EncryptResponse.ProtoReflect.Descriptor instead.
func (*EncryptResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_kms_proto_rawDescGZIP(), []int{1}
}

func (x *EncryptResponse) GetCiphertext() string {
	if x != nil {
		return x.Ciphertext
	}
	return ""
}

func (x *EncryptResponse) GetKeyVersionId() string {
	if x != nil {
		return x.KeyVersionId
	}
	return ""
}

type DecryptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ScopeId       string                 `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	Ciphertext    string                 `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"` // base64-encoded
	Aad           string                 `protobuf:"bytes,4,opt,name=aad,proto3" json:"aad,omitempty"`
	KeyVersionId  string                 `protobuf:"bytes,5,opt,name=key_version_id,json=keyVersionId,proto3" json:"key_version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptRequest) Reset() {
	*x = DecryptRequest{}
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptRequest) ProtoMessage() {}

func (x *DecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptRequest.ProtoReflect.Descriptor instead.
func (*DecryptRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_kms_proto_rawDescGZIP(), []int{2}
}

func (x *DecryptRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *DecryptRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *DecryptRequest) GetCiphertext() string {
	if x != nil {
		return x.Ciphertext
	}
	return ""
}

func (x *DecryptRequest) GetAad() string {
	if x != nil {
		return x.Aad
	}
	return ""
}

func (x *DecryptRequest) GetKeyVersionId() string {
	if x != nil {
		return x.KeyVersionId
	}
	return ""
}

type DecryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     []byte                 `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *DecryptResponse) Reset() {
	*x = DecryptResponse{}
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *DecryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*DecryptResponse) ProtoMessage() {}

func (x *DecryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use DecryptResponse.ProtoReflect.Descriptor instead.
func (*DecryptResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_kms_proto_rawDescGZIP(), []int{3}
}

func (x *DecryptResponse) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

type BatchEncryptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ScopeId       string                 `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	Items         []*BatchEncryptItem    `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEncryptRequest) Reset() {
	*x = BatchEncryptRequest{}
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEncryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEncryptRequest) ProtoMessage() {}

func (x *BatchEncryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEncryptRequest.ProtoReflect.Descriptor instead.
func (*BatchEncryptRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_kms_proto_rawDescGZIP(), []int{4}
}

func (x *BatchEncryptRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BatchEncryptRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *BatchEncryptRequest) GetItems() []*BatchEncryptItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchEncryptItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Plaintext     []byte                 `protobuf:"bytes,1,opt,name=plaintext,proto3" json:"plaintext,omitempty"`
	Aad           string                 `protobuf:"bytes,2,opt,name=aad,proto3" json:"aad,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEncryptItem) Reset() {
	*x = BatchEncryptItem{}
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEncryptItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEncryptItem) ProtoMessage() {}

func (x *BatchEncryptItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEncryptItem.ProtoReflect.Descriptor instead.
func (*BatchEncryptItem) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_kms_proto_rawDescGZIP(), []int{5}
}

func (x *BatchEncryptItem) GetPlaintext() []byte {
	if x != nil {
		return x.Plaintext
	}
	return nil
}

func (x *BatchEncryptItem) GetAad() string {
	if x != nil {
		return x.Aad
	}
	return ""
}

type BatchEncryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*EncryptResponse     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchEncryptResponse) Reset() {
	*x = BatchEncryptResponse{}
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchEncryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchEncryptResponse) ProtoMessage() {}

func (x *BatchEncryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchEncryptResponse.ProtoReflect.Descriptor instead.
func (*BatchEncryptResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_kms_proto_rawDescGZIP(), []int{6}
}

func (x *BatchEncryptResponse) GetItems() []*EncryptResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchDecryptRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ScopeId       string                 `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	Items         []*BatchDecryptItem    `protobuf:"bytes,3,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDecryptRequest) Reset() {
	*x = BatchDecryptRequest{}
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDecryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDecryptRequest) ProtoMessage() {}

func (x *BatchDecryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDecryptRequest.ProtoReflect.Descriptor instead.
func (*BatchDecryptRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_kms_proto_rawDescGZIP(), []int{7}
}

func (x *BatchDecryptRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *BatchDecryptRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *BatchDecryptRequest) GetItems() []*BatchDecryptItem {
	if x != nil {
		return x.Items
	}
	return nil
}

type BatchDecryptItem struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    string                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	Aad           string                 `protobuf:"bytes,2,opt,name=aad,proto3" json:"aad,omitempty"`
	KeyVersionId  string                 `protobuf:"bytes,3,opt,name=key_version_id,json=keyVersionId,proto3" json:"key_version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDecryptItem) Reset() {
	*x = BatchDecryptItem{}
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDecryptItem) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDecryptItem) ProtoMessage() {}

func (x *BatchDecryptItem) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDecryptItem.ProtoReflect.Descriptor instead.
func (*BatchDecryptItem) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_kms_proto_rawDescGZIP(), []int{8}
}

func (x *BatchDecryptItem) GetCiphertext() string {
	if x != nil {
		return x.Ciphertext
	}
	return ""
}

func (x *BatchDecryptItem) GetAad() string {
	if x != nil {
		return x.Aad
	}
	return ""
}

func (x *BatchDecryptItem) GetKeyVersionId() string {
	if x != nil {
		return x.KeyVersionId
	}
	return ""
}

type BatchDecryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Items         []*DecryptResponse     `protobuf:"bytes,1,rep,name=items,proto3" json:"items,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *BatchDecryptResponse) Reset() {
	*x = BatchDecryptResponse{}
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *BatchDecryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*BatchDecryptResponse) ProtoMessage() {}

func (x *BatchDecryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use BatchDecryptResponse.ProtoReflect.Descriptor instead.
func (*BatchDecryptResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_kms_proto_rawDescGZIP(), []int{9}
}

func (x *BatchDecryptResponse) GetItems() []*DecryptResponse {
	if x != nil {
		return x.Items
	}
	return nil
}

type CreateDataKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ScopeId       string                 `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDataKeyRequest) Reset() {
	*x = CreateDataKeyRequest{}
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDataKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDataKeyRequest) ProtoMessage() {}

func (x *CreateDataKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDataKeyRequest.ProtoReflect.Descriptor instead.
func (*CreateDataKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_kms_proto_rawDescGZIP(), []int{10}
}

func (x *CreateDataKeyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *CreateDataKeyRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

type CreateDataKeyResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	KeyVersionId  string                 `protobuf:"bytes,1,opt,name=key_version_id,json=keyVersionId,proto3" json:"key_version_id,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateDataKeyResponse) Reset() {
	*x = CreateDataKeyResponse{}
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateDataKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateDataKeyResponse) ProtoMessage() {}

func (x *CreateDataKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateDataKeyResponse.ProtoReflect.Descriptor instead.
func (*CreateDataKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_kms_proto_rawDescGZIP(), []int{11}
}

func (x *CreateDataKeyResponse) GetKeyVersionId() string {
	if x != nil {
		return x.KeyVersionId
	}
	return ""
}

func (x *CreateDataKeyResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type RotateDataKeyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ScopeId       string                 `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RotateDataKeyRequest) Reset() {
	*x = RotateDataKeyRequest{}
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateDataKeyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateDataKeyRequest) ProtoMessage() {}

func (x *RotateDataKeyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateDataKeyRequest.ProtoReflect.Descriptor instead.
func (*RotateDataKeyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_kms_proto_rawDescGZIP(), []int{12}
}

func (x *RotateDataKeyRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *RotateDataKeyRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

type RotateDataKeyResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	NewKeyVersionId string                 `protobuf:"bytes,1,opt,name=new_key_version_id,json=newKeyVersionId,proto3" json:"new_key_version_id,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *RotateDataKeyResponse) Reset() {
	*x = RotateDataKeyResponse{}
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RotateDataKeyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RotateDataKeyResponse) ProtoMessage() {}

func (x *RotateDataKeyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RotateDataKeyResponse.ProtoReflect.Descriptor instead.
func (*RotateDataKeyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_kms_proto_rawDescGZIP(), []int{13}
}

func (x *RotateDataKeyResponse) GetNewKeyVersionId() string {
	if x != nil {
		return x.NewKeyVersionId
	}
	return ""
}

type ReEncryptRequest struct {
	state              protoimpl.MessageState `protogen:"open.v1"`
	TenantId           string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ScopeId            string                 `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	Ciphertext         string                 `protobuf:"bytes,3,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	SourceAad          string                 `protobuf:"bytes,4,opt,name=source_aad,json=sourceAad,proto3" json:"source_aad,omitempty"`
	TargetAad          string                 `protobuf:"bytes,5,opt,name=target_aad,json=targetAad,proto3" json:"target_aad,omitempty"`
	SourceKeyVersionId string                 `protobuf:"bytes,6,opt,name=source_key_version_id,json=sourceKeyVersionId,proto3" json:"source_key_version_id,omitempty"`
	unknownFields      protoimpl.UnknownFields
	sizeCache          protoimpl.SizeCache
}

func (x *ReEncryptRequest) Reset() {
	*x = ReEncryptRequest{}
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReEncryptRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReEncryptRequest) ProtoMessage() {}

func (x *ReEncryptRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReEncryptRequest.ProtoReflect.Descriptor instead.
func (*ReEncryptRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_kms_proto_rawDescGZIP(), []int{14}
}

func (x *ReEncryptRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *ReEncryptRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *ReEncryptRequest) GetCiphertext() string {
	if x != nil {
		return x.Ciphertext
	}
	return ""
}

func (x *ReEncryptRequest) GetSourceAad() string {
	if x != nil {
		return x.SourceAad
	}
	return ""
}

func (x *ReEncryptRequest) GetTargetAad() string {
	if x != nil {
		return x.TargetAad
	}
	return ""
}

func (x *ReEncryptRequest) GetSourceKeyVersionId() string {
	if x != nil {
		return x.SourceKeyVersionId
	}
	return ""
}

type ReEncryptResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Ciphertext    string                 `protobuf:"bytes,1,opt,name=ciphertext,proto3" json:"ciphertext,omitempty"`
	KeyVersionId  string                 `protobuf:"bytes,2,opt,name=key_version_id,json=keyVersionId,proto3" json:"key_version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ReEncryptResponse) Reset() {
	*x = ReEncryptResponse{}
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ReEncryptResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ReEncryptResponse) ProtoMessage() {}

func (x *ReEncryptResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ReEncryptResponse.ProtoReflect.Descriptor instead.
func (*ReEncryptResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_kms_proto_rawDescGZIP(), []int{15}
}

func (x *ReEncryptResponse) GetCiphertext() string {
	if x != nil {
		return x.Ciphertext
	}
	return ""
}

func (x *ReEncryptResponse) GetKeyVersionId() string {
	if x != nil {
		return x.KeyVersionId
	}
	return ""
}

type GetKeyInfoRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	TenantId      string                 `protobuf:"bytes,1,opt,name=tenant_id,json=tenantId,proto3" json:"tenant_id,omitempty"`
	ScopeId       string                 `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetKeyInfoRequest) Reset() {
	*x = GetKeyInfoRequest{}
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyInfoRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyInfoRequest) ProtoMessage() {}

func (x *GetKeyInfoRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyInfoRequest.ProtoReflect.Descriptor instead.
func (*GetKeyInfoRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_kms_proto_rawDescGZIP(), []int{16}
}

func (x *GetKeyInfoRequest) GetTenantId() string {
	if x != nil {
		return x.TenantId
	}
	return ""
}

func (x *GetKeyInfoRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

type GetKeyInfoResponse struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	KeyVersionId    string                 `protobuf:"bytes,1,opt,name=key_version_id,json=keyVersionId,proto3" json:"key_version_id,omitempty"`
	Version         int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	EncryptionCount int64                  `protobuf:"varint,3,opt,name=encryption_count,json=encryptionCount,proto3" json:"encryption_count,omitempty"`
	MaxEncryptions  int64                  `protobuf:"varint,4,opt,name=max_encryptions,json=maxEncryptions,proto3" json:"max_encryptions,omitempty"`
	Status          string                 `protobuf:"bytes,5,opt,name=status,proto3" json:"status,omitempty"`
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetKeyInfoResponse) Reset() {
	*x = GetKeyInfoResponse{}
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetKeyInfoResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetKeyInfoResponse) ProtoMessage() {}

func (x *GetKeyInfoResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_kms_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetKeyInfoResponse.ProtoReflect.Descriptor instead.
func (*GetKeyInfoResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_kms_proto_rawDescGZIP(), []int{17}
}

func (x *GetKeyInfoResponse) GetKeyVersionId() string {
	if x != nil {
		return x.KeyVersionId
	}
	return ""
}

func (x *GetKeyInfoResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *GetKeyInfoResponse) GetEncryptionCount() int64 {
	if x != nil {
		return x.EncryptionCount
	}
	return 0
}

func (x *GetKeyInfoResponse) GetMaxEncryptions() int64 {
	if x != nil {
		return x.MaxEncryptions
	}
	return 0
}

func (x *GetKeyInfoResponse) GetStatus() string {
	if x != nil {
		return x.Status
	}
	return ""
}

var File_api_proto_minikms_v1_kms_proto protoreflect.FileDescriptor

const file_api_proto_minikms_v1_kms_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/minikms/v1/kms.proto\x12\n" +
	"minikms.v1\"x\n" +
	"\x0eEncryptRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\x12\x1c\n" +
	"\tplaintext\x18\x03 \x01(\fR\tplaintext\x12\x10\n" +
	"\x03aad\x18\x04 \x01(\tR\x03aad\"W\n" +
	"\x0fEncryptResponse\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\tR\n" +
	"ciphertext\x12$\n" +
	"\x0ekey_version_id\x18\x02 \x01(\tR\fkeyVersionId\"\xa0\x01\n" +
	"\x0eDecryptRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x03 \x01(\tR\n" +
	"ciphertext\x12\x10\n" +
	"\x03aad\x18\x04 \x01(\tR\x03aad\x12$\n" +
	"\x0ekey_version_id\x18\x05 \x01(\tR\fkeyVersionId\"/\n" +
	"\x0fDecryptResponse\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\fR\tplaintext\"\x81\x01\n" +
	"\x13BatchEncryptRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\x122\n" +
	"\x05items\x18\x03 \x03(\v2\x1c.minikms.v1.BatchEncryptItemR\x05items\"B\n" +
	"\x10BatchEncryptItem\x12\x1c\n" +
	"\tplaintext\x18\x01 \x01(\fR\tplaintext\x12\x10\n" +
	"\x03aad\x18\x02 \x01(\tR\x03aad\"I\n" +
	"\x14BatchEncryptResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.minikms.v1.EncryptResponseR\x05items\"\x81\x01\n" +
	"\x13BatchDecryptRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\x122\n" +
	"\x05items\x18\x03 \x03(\v2\x1c.minikms.v1.BatchDecryptItemR\x05items\"j\n" +
	"\x10BatchDecryptItem\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\tR\n" +
	"ciphertext\x12\x10\n" +
	"\x03aad\x18\x02 \x01(\tR\x03aad\x12$\n" +
	"\x0ekey_version_id\x18\x03 \x01(\tR\fkeyVersionId\"I\n" +
	"\x14BatchDecryptResponse\x121\n" +
	"\x05items\x18\x01 \x03(\v2\x1b.minikms.v1.DecryptResponseR\x05items\"N\n" +
	"\x14CreateDataKeyRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\"W\n" +
	"\x15CreateDataKeyResponse\x12$\n" +
	"\x0ekey_version_id\x18\x01 \x01(\tR\fkeyVersionId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\"N\n" +
	"\x14RotateDataKeyRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\"D\n" +
	"\x15RotateDataKeyResponse\x12+\n" +
	"\x12new_key_version_id\x18\x01 \x01(\tR\x0fnewKeyVersionId\"\xdb\x01\n" +
	"\x10ReEncryptRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x03 \x01(\tR\n" +
	"ciphertext\x12\x1d\n" +
	"\n" +
	"source_aad\x18\x04 \x01(\tR\tsourceAad\x12\x1d\n" +
	"\n" +
	"target_aad\x18\x05 \x01(\tR\ttargetAad\x121\n" +
	"\x15source_key_version_id\x18\x06 \x01(\tR\x12sourceKeyVersionId\"Y\n" +
	"\x11ReEncryptResponse\x12\x1e\n" +
	"\n" +
	"ciphertext\x18\x01 \x01(\tR\n" +
	"ciphertext\x12$\n" +
	"\x0ekey_version_id\x18\x02 \x01(\tR\fkeyVersionId\"K\n" +
	"\x11GetKeyInfoRequest\x12\x1b\n" +
	"\ttenant_id\x18\x01 \x01(\tR\btenantId\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\"\xc0\x01\n" +
	"\x12GetKeyInfoResponse\x12$\n" +
	"\x0ekey_version_id\x18\x01 \x01(\tR\fkeyVersionId\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12)\n" +
	"\x10encryption_count\x18\x03 \x01(\x03R\x0fencryptionCount\x12'\n" +
	"\x0fmax_encryptions\x18\x04 \x01(\x03R\x0emaxEncryptions\x12\x16\n" +
	"\x06status\x18\x05 \x01(\tR\x06status2\xfd\x04\n" +
	"\n" +
	"KMSService\x12B\n" +
	"\aEncrypt\x12\x1a.minikms.v1.EncryptRequest\x1a\x1b.minikms.v1.EncryptResponse\x12B\n" +
	"\aDecrypt\x12\x1a.minikms.v1.DecryptRequest\x1a\x1b.minikms.v1.DecryptResponse\x12Q\n" +
	"\fBatchEncrypt\x12\x1f.minikms.v1.BatchEncryptRequest\x1a .minikms.v1.BatchEncryptResponse\x12Q\n" +
	"\fBatchDecrypt\x12\x1f.minikms.v1.BatchDecryptRequest\x1a .minikms.v1.BatchDecryptResponse\x12T\n" +
	"\rCreateDataKey\x12 .minikms.v1.CreateDataKeyRequest\x1a!.minikms.v1.CreateDataKeyResponse\x12T\n" +
	"\rRotateDataKey\x12 .minikms.v1.RotateDataKeyRequest\x1a!.minikms.v1.RotateDataKeyResponse\x12H\n" +
	"\tReEncrypt\x12\x1c.minikms.v1.ReEncryptRequest\x1a\x1d.minikms.v1.ReEncryptResponse\x12K\n" +
	"\n" +
	"GetKeyInfo\x12\x1d.minikms.v1.GetKeyInfoRequest\x1a\x1e.minikms.v1.GetKeyInfoResponseB;Z9github.com/envsync-cloud/minikms/api/proto/minikms/v1;minikmsv1b\x06proto3"

var (
	file_api_proto_minikms_v1_kms_proto_rawDescOnce sync.Once
	file_api_proto_minikms_v1_kms_proto_rawDescData []byte
)

func file_api_proto_minikms_v1_kms_proto_rawDescGZIP() []byte {
	file_api_proto_minikms_v1_kms_proto_rawDescOnce.Do(func() {
		file_api_proto_minikms_v1_kms_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_minikms_v1_kms_proto_rawDesc), len(file_api_proto_minikms_v1_kms_proto_rawDesc)))
	})
	return file_api_proto_minikms_v1_kms_proto_rawDescData
}

var file_api_proto_minikms_v1_kms_proto_msgTypes = make([]protoimpl.MessageInfo, 18)
var file_api_proto_minikms_v1_kms_proto_goTypes = []any{
	(*EncryptRequest)(nil),        // 0: minikms.v1.EncryptRequest
	(*EncryptResponse)(nil),       // 1: minikms.v1.EncryptResponse
	(*DecryptRequest)(nil),        // 2: minikms.v1.DecryptRequest
	(*DecryptResponse)(nil),       // 3: minikms.v1.DecryptResponse
	(*BatchEncryptRequest)(nil),   // 4: minikms.v1.BatchEncryptRequest
	(*BatchEncryptItem)(nil),      // 5: minikms.v1.BatchEncryptItem
	(*BatchEncryptResponse)(nil),  // 6: minikms.v1.BatchEncryptResponse
	(*BatchDecryptRequest)(nil),   // 7: minikms.v1.BatchDecryptRequest
	(*BatchDecryptItem)(nil),      // 8: minikms.v1.BatchDecryptItem
	(*BatchDecryptResponse)(nil),  // 9: minikms.v1.BatchDecryptResponse
	(*CreateDataKeyRequest)(nil),  // 10: minikms.v1.CreateDataKeyRequest
	(*CreateDataKeyResponse)(nil), // 11: minikms.v1.CreateDataKeyResponse
	(*RotateDataKeyRequest)(nil),  // 12: minikms.v1.RotateDataKeyRequest
	(*RotateDataKeyResponse)(nil), // 13: minikms.v1.RotateDataKeyResponse
	(*ReEncryptRequest)(nil),      // 14: minikms.v1.ReEncryptRequest
	(*ReEncryptResponse)(nil),     // 15: minikms.v1.ReEncryptResponse
	(*GetKeyInfoRequest)(nil),     // 16: minikms.v1.GetKeyInfoRequest
	(*GetKeyInfoResponse)(nil),    // 17: minikms.v1.GetKeyInfoResponse
}
var file_api_proto_minikms_v1_kms_proto_depIdxs = []int32{
	5,  // 0: minikms.v1.BatchEncryptRequest.items:type_name -> minikms.v1.BatchEncryptItem
	1,  // 1: minikms.v1.BatchEncryptResponse.items:type_name -> minikms.v1.EncryptResponse
	8,  // 2: minikms.v1.BatchDecryptRequest.items:type_name -> minikms.v1.BatchDecryptItem
	3,  // 3: minikms.v1.BatchDecryptResponse.items:type_name -> minikms.v1.DecryptResponse
	0,  // 4: minikms.v1.KMSService.Encrypt:input_type -> minikms.v1.EncryptRequest
	2,  // 5: minikms.v1.KMSService.Decrypt:input_type -> minikms.v1.DecryptRequest
	4,  // 6: minikms.v1.KMSService.BatchEncrypt:input_type -> minikms.v1.BatchEncryptRequest
	7,  // 7: minikms.v1.KMSService.BatchDecrypt:input_type -> minikms.v1.BatchDecryptRequest
	10, // 8: minikms.v1.KMSService.CreateDataKey:input_type -> minikms.v1.CreateDataKeyRequest
	12, // 9: minikms.v1.KMSService.RotateDataKey:input_type -> minikms.v1.RotateDataKeyRequest
	14, // 10: minikms.v1.KMSService.ReEncrypt:input_type -> minikms.v1.ReEncryptRequest
	16, // 11: minikms.v1.KMSService.GetKeyInfo:input_type -> minikms.v1.GetKeyInfoRequest
	1,  // 12: minikms.v1.KMSService.Encrypt:output_type -> minikms.v1.EncryptResponse
	3,  // 13: minikms.v1.KMSService.Decrypt:output_type -> minikms.v1.DecryptResponse
	6,  // 14: minikms.v1.KMSService.BatchEncrypt:output_type -> minikms.v1.BatchEncryptResponse
	9,  // 15: minikms.v1.KMSService.BatchDecrypt:output_type -> minikms.v1.BatchDecryptResponse
	11, // 16: minikms.v1.KMSService.CreateDataKey:output_type -> minikms.v1.CreateDataKeyResponse
	13, // 17: minikms.v1.KMSService.RotateDataKey:output_type -> minikms.v1.RotateDataKeyResponse
	15, // 18: minikms.v1.KMSService.ReEncrypt:output_type -> minikms.v1.ReEncryptResponse
	17, // 19: minikms.v1.KMSService.GetKeyInfo:output_type -> minikms.v1.GetKeyInfoResponse
	12, // [12:20] is the sub-list for method output_type
	4,  // [4:12] is the sub-list for method input_type
	4,  // [4:4] is the sub-list for extension type_name
	4,  // [4:4] is the sub-list for extension extendee
	0,  // [0:4] is the sub-list for field type_name
}

func init() { file_api_proto_minikms_v1_kms_proto_init() }
func file_api_proto_minikms_v1_kms_proto_init() {
	if File_api_proto_minikms_v1_kms_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_minikms_v1_kms_proto_rawDesc), len(file_api_proto_minikms_v1_kms_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   18,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_minikms_v1_kms_proto_goTypes,
		DependencyIndexes: file_api_proto_minikms_v1_kms_proto_depIdxs,
		MessageInfos:      file_api_proto_minikms_v1_kms_proto_msgTypes,
	}.Build()
	File_api_proto_minikms_v1_kms_proto = out.File
	file_api_proto_minikms_v1_kms_proto_goTypes = nil
	file_api_proto_minikms_v1_kms_proto_depIdxs = nil
}
