// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/proto/minikms/v1/kms.proto

package minikmsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	KMSService_Encrypt_FullMethodName       = "/minikms.v1.KMSService/Encrypt"
	KMSService_Decrypt_FullMethodName       = "/minikms.v1.KMSService/Decrypt"
	KMSService_BatchEncrypt_FullMethodName  = "/minikms.v1.KMSService/BatchEncrypt"
	KMSService_BatchDecrypt_FullMethodName  = "/minikms.v1.KMSService/BatchDecrypt"
	KMSService_CreateDataKey_FullMethodName = "/minikms.v1.KMSService/CreateDataKey"
	KMSService_RotateDataKey_FullMethodName = "/minikms.v1.KMSService/RotateDataKey"
	KMSService_ReEncrypt_FullMethodName     = "/minikms.v1.KMSService/ReEncrypt"
	KMSService_GetKeyInfo_FullMethodName    = "/minikms.v1.KMSService/GetKeyInfo"
)

// KMSServiceClient is the client API for KMSService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// KMSService provides encrypt/decrypt operations using managed data encryption keys.
// Callers never see root key or plaintext DEKs — all operations go through this service.
type KMSServiceClient interface {
	Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error)
	Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error)
	BatchEncrypt(ctx context.Context, in *BatchEncryptRequest, opts ...grpc.CallOption) (*BatchEncryptResponse, error)
	BatchDecrypt(ctx context.Context, in *BatchDecryptRequest, opts ...grpc.CallOption) (*BatchDecryptResponse, error)
	CreateDataKey(ctx context.Context, in *CreateDataKeyRequest, opts ...grpc.CallOption) (*CreateDataKeyResponse, error)
	RotateDataKey(ctx context.Context, in *RotateDataKeyRequest, opts ...grpc.CallOption) (*RotateDataKeyResponse, error)
	ReEncrypt(ctx context.Context, in *ReEncryptRequest, opts ...grpc.CallOption) (*ReEncryptResponse, error)
	GetKeyInfo(ctx context.Context, in *GetKeyInfoRequest, opts ...grpc.CallOption) (*GetKeyInfoResponse, error)
}

type kMSServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewKMSServiceClient(cc grpc.ClientConnInterface) KMSServiceClient {
	return &kMSServiceClient{cc}
}

func (c *kMSServiceClient) Encrypt(ctx context.Context, in *EncryptRequest, opts ...grpc.CallOption) (*EncryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(EncryptResponse)
	err := c.cc.Invoke(ctx, KMSService_Encrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kMSServiceClient) Decrypt(ctx context.Context, in *DecryptRequest, opts ...grpc.CallOption) (*DecryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(DecryptResponse)
	err := c.cc.Invoke(ctx, KMSService_Decrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kMSServiceClient) BatchEncrypt(ctx context.Context, in *BatchEncryptRequest, opts ...grpc.CallOption) (*BatchEncryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchEncryptResponse)
	err := c.cc.Invoke(ctx, KMSService_BatchEncrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kMSServiceClient) BatchDecrypt(ctx context.Context, in *BatchDecryptRequest, opts ...grpc.CallOption) (*BatchDecryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(BatchDecryptResponse)
	err := c.cc.Invoke(ctx, KMSService_BatchDecrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kMSServiceClient) CreateDataKey(ctx context.Context, in *CreateDataKeyRequest, opts ...grpc.CallOption) (*CreateDataKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateDataKeyResponse)
	err := c.cc.Invoke(ctx, KMSService_CreateDataKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kMSServiceClient) RotateDataKey(ctx context.Context, in *RotateDataKeyRequest, opts ...grpc.CallOption) (*RotateDataKeyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RotateDataKeyResponse)
	err := c.cc.Invoke(ctx, KMSService_RotateDataKey_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kMSServiceClient) ReEncrypt(ctx context.Context, in *ReEncryptRequest, opts ...grpc.CallOption) (*ReEncryptResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(ReEncryptResponse)
	err := c.cc.Invoke(ctx, KMSService_ReEncrypt_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *kMSServiceClient) GetKeyInfo(ctx context.Context, in *GetKeyInfoRequest, opts ...grpc.CallOption) (*GetKeyInfoResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetKeyInfoResponse)
	err := c.cc.Invoke(ctx, KMSService_GetKeyInfo_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// KMSServiceServer is the server API for KMSService service.
// All implementations must embed UnimplementedKMSServiceServer
// for forward compatibility.
//
// KMSService provides encrypt/decrypt operations using managed data encryption keys.
// Callers never see root key or plaintext DEKs — all operations go through this service.
type KMSServiceServer interface {
	Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error)
	Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error)
	BatchEncrypt(context.Context, *BatchEncryptRequest) (*BatchEncryptResponse, error)
	BatchDecrypt(context.Context, *BatchDecryptRequest) (*BatchDecryptResponse, error)
	CreateDataKey(context.Context, *CreateDataKeyRequest) (*CreateDataKeyResponse, error)
	RotateDataKey(context.Context, *RotateDataKeyRequest) (*RotateDataKeyResponse, error)
	ReEncrypt(context.Context, *ReEncryptRequest) (*ReEncryptResponse, error)
	GetKeyInfo(context.Context, *GetKeyInfoRequest) (*GetKeyInfoResponse, error)
	mustEmbedUnimplementedKMSServiceServer()
}

// UnimplementedKMSServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedKMSServiceServer struct{}

func (UnimplementedKMSServiceServer) Encrypt(context.Context, *EncryptRequest) (*EncryptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Encrypt not implemented")
}
func (UnimplementedKMSServiceServer) Decrypt(context.Context, *DecryptRequest) (*DecryptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Decrypt not implemented")
}
func (UnimplementedKMSServiceServer) BatchEncrypt(context.Context, *BatchEncryptRequest) (*BatchEncryptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchEncrypt not implemented")
}
func (UnimplementedKMSServiceServer) BatchDecrypt(context.Context, *BatchDecryptRequest) (*BatchDecryptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method BatchDecrypt not implemented")
}
func (UnimplementedKMSServiceServer) CreateDataKey(context.Context, *CreateDataKeyRequest) (*CreateDataKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateDataKey not implemented")
}
func (UnimplementedKMSServiceServer) RotateDataKey(context.Context, *RotateDataKeyRequest) (*RotateDataKeyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RotateDataKey not implemented")
}
func (UnimplementedKMSServiceServer) ReEncrypt(context.Context, *ReEncryptRequest) (*ReEncryptResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReEncrypt not implemented")
}
func (UnimplementedKMSServiceServer) GetKeyInfo(context.Context, *GetKeyInfoRequest) (*GetKeyInfoResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetKeyInfo not implemented")
}
func (UnimplementedKMSServiceServer) mustEmbedUnimplementedKMSServiceServer() {}
func (UnimplementedKMSServiceServer) testEmbeddedByValue()                    {}

// UnsafeKMSServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to KMSServiceServer will
// result in compilation errors.
type UnsafeKMSServiceServer interface {
	mustEmbedUnimplementedKMSServiceServer()
}

func RegisterKMSServiceServer(s grpc.ServiceRegistrar, srv KMSServiceServer) {
	// If the following call panics, it indicates UnimplementedKMSServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&KMSService_ServiceDesc, srv)
}

func _KMSService_Encrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(EncryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSServiceServer).Encrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMSService_Encrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSServiceServer).Encrypt(ctx, req.(*EncryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KMSService_Decrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(DecryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSServiceServer).Decrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMSService_Decrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSServiceServer).Decrypt(ctx, req.(*DecryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KMSService_BatchEncrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchEncryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSServiceServer).BatchEncrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMSService_BatchEncrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSServiceServer).BatchEncrypt(ctx, req.(*BatchEncryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KMSService_BatchDecrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(BatchDecryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSServiceServer).BatchDecrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMSService_BatchDecrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSServiceServer).BatchDecrypt(ctx, req.(*BatchDecryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KMSService_CreateDataKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateDataKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSServiceServer).CreateDataKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMSService_CreateDataKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSServiceServer).CreateDataKey(ctx, req.(*CreateDataKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KMSService_RotateDataKey_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RotateDataKeyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSServiceServer).RotateDataKey(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMSService_RotateDataKey_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSServiceServer).RotateDataKey(ctx, req.(*RotateDataKeyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KMSService_ReEncrypt_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(ReEncryptRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSServiceServer).ReEncrypt(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMSService_ReEncrypt_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSServiceServer).ReEncrypt(ctx, req.(*ReEncryptRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _KMSService_GetKeyInfo_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetKeyInfoRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(KMSServiceServer).GetKeyInfo(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: KMSService_GetKeyInfo_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(KMSServiceServer).GetKeyInfo(ctx, req.(*GetKeyInfoRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// KMSService_ServiceDesc is the grpc.ServiceDesc for KMSService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var KMSService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "minikms.v1.KMSService",
	HandlerType: (*KMSServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Encrypt",
			Handler:    _KMSService_Encrypt_Handler,
		},
		{
			MethodName: "Decrypt",
			Handler:    _KMSService_Decrypt_Handler,
		},
		{
			MethodName: "BatchEncrypt",
			Handler:    _KMSService_BatchEncrypt_Handler,
		},
		{
			MethodName: "BatchDecrypt",
			Handler:    _KMSService_BatchDecrypt_Handler,
		},
		{
			MethodName: "CreateDataKey",
			Handler:    _KMSService_CreateDataKey_Handler,
		},
		{
			MethodName: "RotateDataKey",
			Handler:    _KMSService_RotateDataKey_Handler,
		},
		{
			MethodName: "ReEncrypt",
			Handler:    _KMSService_ReEncrypt_Handler,
		},
		{
			MethodName: "GetKeyInfo",
			Handler:    _KMSService_GetKeyInfo_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/minikms/v1/kms.proto",
}
