// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/minikms/v1/pki.proto

package minikmsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrgCARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	OrgName       string                 `protobuf:"bytes,2,opt,name=org_name,json=orgName,proto3" json:"org_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrgCARequest) Reset() {
	*x = CreateOrgCARequest{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrgCARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrgCARequest) ProtoMessage() {}

func (x *CreateOrgCARequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrgCARequest.ProtoReflect.Descriptor instead.
func (*CreateOrgCARequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrgCARequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CreateOrgCARequest) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

type CreateOrgCAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertPem       string                 `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	SerialHex     string                 `protobuf:"bytes,2,opt,name=serial_hex,json=serialHex,proto3" json:"serial_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrgCAResponse) Reset() {
	*x = CreateOrgCAResponse{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrgCAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrgCAResponse) ProtoMessage() {}

func (x *CreateOrgCAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrgCAResponse.ProtoReflect.Descriptor instead.
func (*CreateOrgCAResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrgCAResponse) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *CreateOrgCAResponse) GetSerialHex() string {
	if x != nil {
		return x.SerialHex
	}
	return ""
}

type IssueMemberCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	MemberEmail   string                 `protobuf:"bytes,2,opt,name=member_email,json=memberEmail,proto3" json:"member_email,omitempty"`
	OrgId         string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueMemberCertRequest) Reset() {
	*x = IssueMemberCertRequest{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueMemberCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueMemberCertRequest) ProtoMessage() {}

func (x *IssueMemberCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueMemberCertRequest.ProtoReflect.Descriptor instead.
func (*IssueMemberCertRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{2}
}

func (x *IssueMemberCertRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *IssueMemberCertRequest) GetMemberEmail() string {
	if x != nil {
		return x.MemberEmail
	}
	return ""
}

func (x *IssueMemberCertRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *IssueMemberCertRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type IssueMemberCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertPem       string                 `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	KeyPem        string                 `protobuf:"bytes,2,opt,name=key_pem,json=keyPem,proto3" json:"key_pem,omitempty"`
	SerialHex     string                 `protobuf:"bytes,3,opt,name=serial_hex,json=serialHex,proto3" json:"serial_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueMemberCertResponse) Reset() {
	*x = IssueMemberCertResponse{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueMemberCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueMemberCertResponse) ProtoMessage() {}

func (x *IssueMemberCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueMemberCertResponse.ProtoReflect.Descriptor instead.
func (*IssueMemberCertResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{3}
}

func (x *IssueMemberCertResponse) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *IssueMemberCertResponse) GetKeyPem() string {
	if x != nil {
		return x.KeyPem
	}
	return ""
}

func (x *IssueMemberCertResponse) GetSerialHex() string {
	if x != nil {
		return x.SerialHex
	}
	return ""
}

type RevokeCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerialHex     string                 `protobuf:"bytes,1,opt,name=serial_hex,json=serialHex,proto3" json:"serial_hex,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Reason        int32                  `protobuf:"varint,3,opt,name=reason,proto3" json:"reason,omitempty"` // RFC 5280 reason code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCertRequest) Reset() {
	*x = RevokeCertRequest{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCertRequest) ProtoMessage() {}

func (x *RevokeCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCertRequest.ProtoReflect.Descriptor instead.
func (*RevokeCertRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{4}
}

func (x *RevokeCertRequest) GetSerialHex() string {
	if x != nil {
		return x.SerialHex
	}
	return ""
}

func (x *RevokeCertRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *RevokeCertRequest) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

type RevokeCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCertResponse) Reset() {
	*x = RevokeCertResponse{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCertResponse) ProtoMessage() {}

func (x *RevokeCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCertResponse.ProtoReflect.Descriptor instead.
func (*RevokeCertResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{5}
}

func (x *RevokeCertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetCRLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	DeltaOnly     bool                   `protobuf:"varint,2,opt,name=delta_only,json=deltaOnly,proto3" json:"delta_only,omitempty"` // If true, return only delta CRL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCRLRequest) Reset() {
	*x = GetCRLRequest{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCRLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCRLRequest) ProtoMessage() {}

func (x *GetCRLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCRLRequest.ProtoReflect.Descriptor instead.
func (*GetCRLRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{6}
}

func (x *GetCRLRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *GetCRLRequest) GetDeltaOnly() bool {
	if x != nil {
		return x.DeltaOnly
	}
	return false
}

type GetCRLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CrlDer        []byte                 `protobuf:"bytes,1,opt,name=crl_der,json=crlDer,proto3" json:"crl_der,omitempty"`
	CrlNumber     int64                  `protobuf:"varint,2,opt,name=crl_number,json=crlNumber,proto3" json:"crl_number,omitempty"`
	IsDelta       bool                   `protobuf:"varint,3,opt,name=is_delta,json=isDelta,proto3" json:"is_delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCRLResponse) Reset() {
	*x = GetCRLResponse{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCRLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCRLResponse) ProtoMessage() {}

func (x *GetCRLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCRLResponse.ProtoReflect.Descriptor instead.
func (*GetCRLResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{7}
}

func (x *GetCRLResponse) GetCrlDer() []byte {
	if x != nil {
		return x.CrlDer
	}
	return nil
}

func (x *GetCRLResponse) GetCrlNumber() int64 {
	if x != nil {
		return x.CrlNumber
	}
	return 0
}

func (x *GetCRLResponse) GetIsDelta() bool {
	if x != nil {
		return x.IsDelta
	}
	return false
}

type CheckOCSPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerialHex     string                 `protobuf:"bytes,1,opt,name=serial_hex,json=serialHex,proto3" json:"serial_hex,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOCSPRequest) Reset() {
	*x = CheckOCSPRequest{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOCSPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOCSPRequest) ProtoMessage() {}

func (x *CheckOCSPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOCSPRequest.ProtoReflect.Descriptor instead.
func (*CheckOCSPRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{8}
}

func (x *CheckOCSPRequest) GetSerialHex() string {
	if x != nil {
		return x.SerialHex
	}
	return ""
}

func (x *CheckOCSPRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type CheckOCSPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`                       // 0=good, 1=revoked, 2=unknown
	RevokedAt     string                 `protobuf:"bytes,2,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"` // RFC3339, empty if not revoked
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOCSPResponse) Reset() {
	*x = CheckOCSPResponse{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOCSPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOCSPResponse) ProtoMessage() {}

func (x *CheckOCSPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOCSPResponse.ProtoReflect.Descriptor instead.
func (*CheckOCSPResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{9}
}

func (x *CheckOCSPResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CheckOCSPResponse) GetRevokedAt() string {
	if x != nil {
		return x.RevokedAt
	}
	return ""
}

type GetRootCARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRootCARequest) Reset() {
	*x = GetRootCARequest{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRootCARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRootCARequest) ProtoMessage() {}

func (x *GetRootCARequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRootCARequest.ProtoReflect.Descriptor instead.
func (*GetRootCARequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{10}
}

type GetRootCAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertPem       string                 `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRootCAResponse) Reset() {
	*x = GetRootCAResponse{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRootCAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRootCAResponse) ProtoMessage() {}

func (x *GetRootCAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRootCAResponse.ProtoReflect.Descriptor instead.
func (*GetRootCAResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{11}
}

func (x *GetRootCAResponse) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

var File_api_proto_minikms_v1_pki_proto protoreflect.FileDescriptor

const file_api_proto_minikms_v1_pki_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/minikms/v1/pki.proto\x12\n" +
	"minikms.v1\"F\n" +
	"\x12CreateOrgCARequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\borg_name\x18\x02 \x01(\tR\aorgName\"O\n" +
	"\x13CreateOrgCAResponse\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\tR\acertPem\x12\x1d\n" +
	"\n" +
	"serial_hex\x18\x02 \x01(\tR\tserialHex\"\x83\x01\n" +
	"\x16IssueMemberCertRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12!\n" +
	"\fmember_email\x18\x02 \x01(\tR\vmemberEmail\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"l\n" +
	"\x17IssueMemberCertResponse\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\tR\acertPem\x12\x17\n" +
	"\akey_pem\x18\x02 \x01(\tR\x06keyPem\x12\x1d\n" +
	"\n" +
	"serial_hex\x18\x03 \x01(\tR\tserialHex\"a\n" +
	"\x11RevokeCertRequest\x12\x1d\n" +
	"\n" +
	"serial_hex\x18\x01 \x01(\tR\tserialHex\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\x05R\x06reason\".\n" +
	"\x12RevokeCertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"E\n" +
	"\rGetCRLRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"delta_only\x18\x02 \x01(\bR\tdeltaOnly\"c\n" +
	"\x0eGetCRLResponse\x12\x17\n" +
	"\acrl_der\x18\x01 \x01(\fR\x06crlDer\x12\x1d\n" +
	"\n" +
	"crl_number\x18\x02 \x01(\x03R\tcrlNumber\x12\x19\n" +
	"\bis_delta\x18\x03 \x01(\bR\aisDelta\"H\n" +
	"\x10CheckOCSPRequest\x12\x1d\n" +
	"\n" +
	"serial_hex\x18\x01 \x01(\tR\tserialHex\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\"J\n" +
	"\x11CheckOCSPResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"revoked_at\x18\x02 \x01(\tR\trevokedAt\"\x12\n" +
	"\x10GetRootCARequest\".\n" +
	"\x11GetRootCAResponse\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\tR\acertPem2\xda\x03\n" +
	"\n" +
	"PKIService\x12N\n" +
	"\vCreateOrgCA\x12\x1e.minikms.v1.CreateOrgCARequest\x1a\x1f.minikms.v1.CreateOrgCAResponse\x12Z\n" +
	"\x0fIssueMemberCert\x12\".minikms.v1.IssueMemberCertRequest\x1a#.minikms.v1.IssueMemberCertResponse\x12K\n" +
	"\n" +
	"RevokeCert\x12\x1d.minikms.v1.RevokeCertRequest\x1a\x1e.minikms.v1.RevokeCertResponse\x12?\n" +
	"\x06GetCRL\x12\x19.minikms.v1.GetCRLRequest\x1a\x1a.minikms.v1.GetCRLResponse\x12H\n" +
	"\tCheckOCSP\x12\x1c.minikms.v1.CheckOCSPRequest\x1a\x1d.minikms.v1.CheckOCSPResponse\x12H\n" +
	"\tGetRootCA\x12\x1c.minikms.v1.GetRootCARequest\x1a\x1d.minikms.v1.GetRootCAResponseB;Z9github.com/envsync/minikms/api/proto/minikms/v1;minikmsv1b\x06proto3"

var (
	file_api_proto_minikms_v1_pki_proto_rawDescOnce sync.Once
	file_api_proto_minikms_v1_pki_proto_rawDescData []byte
)

func file_api_proto_minikms_v1_pki_proto_rawDescGZIP() []byte {
	file_api_proto_minikms_v1_pki_proto_rawDescOnce.Do(func() {
		file_api_proto_minikms_v1_pki_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_minikms_v1_pki_proto_rawDesc), len(file_api_proto_minikms_v1_pki_proto_rawDesc)))
	})
	return file_api_proto_minikms_v1_pki_proto_rawDescData
}

var file_api_proto_minikms_v1_pki_proto_msgTypes = make([]protoimpl.MessageInfo, 12)
var file_api_proto_minikms_v1_pki_proto_goTypes = []any{
	(*CreateOrgCARequest)(nil),      // 0: minikms.v1.CreateOrgCARequest
	(*CreateOrgCAResponse)(nil),     // 1: minikms.v1.CreateOrgCAResponse
	(*IssueMemberCertRequest)(nil),  // 2: minikms.v1.IssueMemberCertRequest
	(*IssueMemberCertResponse)(nil), // 3: minikms.v1.IssueMemberCertResponse
	(*RevokeCertRequest)(nil),       // 4: minikms.v1.RevokeCertRequest
	(*RevokeCertResponse)(nil),      // 5: minikms.v1.RevokeCertResponse
	(*GetCRLRequest)(nil),           // 6: minikms.v1.GetCRLRequest
	(*GetCRLResponse)(nil),          // 7: minikms.v1.GetCRLResponse
	(*CheckOCSPRequest)(nil),        // 8: minikms.v1.CheckOCSPRequest
	(*CheckOCSPResponse)(nil),       // 9: minikms.v1.CheckOCSPResponse
	(*GetRootCARequest)(nil),        // 10: minikms.v1.GetRootCARequest
	(*GetRootCAResponse)(nil),       // 11: minikms.v1.GetRootCAResponse
}
var file_api_proto_minikms_v1_pki_proto_depIdxs = []int32{
	0,  // 0: minikms.v1.PKIService.CreateOrgCA:input_type -> minikms.v1.CreateOrgCARequest
	2,  // 1: minikms.v1.PKIService.IssueMemberCert:input_type -> minikms.v1.IssueMemberCertRequest
	4,  // 2: minikms.v1.PKIService.RevokeCert:input_type -> minikms.v1.RevokeCertRequest
	6,  // 3: minikms.v1.PKIService.GetCRL:input_type -> minikms.v1.GetCRLRequest
	8,  // 4: minikms.v1.PKIService.CheckOCSP:input_type -> minikms.v1.CheckOCSPRequest
	10, // 5: minikms.v1.PKIService.GetRootCA:input_type -> minikms.v1.GetRootCARequest
	1,  // 6: minikms.v1.PKIService.CreateOrgCA:output_type -> minikms.v1.CreateOrgCAResponse
	3,  // 7: minikms.v1.PKIService.IssueMemberCert:output_type -> minikms.v1.IssueMemberCertResponse
	5,  // 8: minikms.v1.PKIService.RevokeCert:output_type -> minikms.v1.RevokeCertResponse
	7,  // 9: minikms.v1.PKIService.GetCRL:output_type -> minikms.v1.GetCRLResponse
	9,  // 10: minikms.v1.PKIService.CheckOCSP:output_type -> minikms.v1.CheckOCSPResponse
	11, // 11: minikms.v1.PKIService.GetRootCA:output_type -> minikms.v1.GetRootCAResponse
	6,  // [6:12] is the sub-list for method output_type
	0,  // [0:6] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_minikms_v1_pki_proto_init() }
func file_api_proto_minikms_v1_pki_proto_init() {
	if File_api_proto_minikms_v1_pki_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_minikms_v1_pki_proto_rawDesc), len(file_api_proto_minikms_v1_pki_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   12,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_minikms_v1_pki_proto_goTypes,
		DependencyIndexes: file_api_proto_minikms_v1_pki_proto_depIdxs,
		MessageInfos:      file_api_proto_minikms_v1_pki_proto_msgTypes,
	}.Build()
	File_api_proto_minikms_v1_pki_proto = out.File
	file_api_proto_minikms_v1_pki_proto_goTypes = nil
	file_api_proto_minikms_v1_pki_proto_depIdxs = nil
}
