// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/minikms/v1/pki.proto

package minikmsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type CreateOrgCARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	OrgName       string                 `protobuf:"bytes,2,opt,name=org_name,json=orgName,proto3" json:"org_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrgCARequest) Reset() {
	*x = CreateOrgCARequest{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrgCARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrgCARequest) ProtoMessage() {}

func (x *CreateOrgCARequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrgCARequest.ProtoReflect.Descriptor instead.
func (*CreateOrgCARequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{0}
}

func (x *CreateOrgCARequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CreateOrgCARequest) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

type CreateOrgCAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertPem       string                 `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	SerialHex     string                 `protobuf:"bytes,2,opt,name=serial_hex,json=serialHex,proto3" json:"serial_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrgCAResponse) Reset() {
	*x = CreateOrgCAResponse{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrgCAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrgCAResponse) ProtoMessage() {}

func (x *CreateOrgCAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrgCAResponse.ProtoReflect.Descriptor instead.
func (*CreateOrgCAResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{1}
}

func (x *CreateOrgCAResponse) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *CreateOrgCAResponse) GetSerialHex() string {
	if x != nil {
		return x.SerialHex
	}
	return ""
}

type CreateOrgCACSRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	OrgName       string                 `protobuf:"bytes,2,opt,name=org_name,json=orgName,proto3" json:"org_name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrgCACSRRequest) Reset() {
	*x = CreateOrgCACSRRequest{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrgCACSRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrgCACSRRequest) ProtoMessage() {}

func (x *CreateOrgCACSRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrgCACSRRequest.ProtoReflect.Descriptor instead.
func (*CreateOrgCACSRRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{2}
}

func (x *CreateOrgCACSRRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CreateOrgCACSRRequest) GetOrgName() string {
	if x != nil {
		return x.OrgName
	}
	return ""
}

type CreateOrgCACSRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CsrPem        string                 `protobuf:"bytes,1,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateOrgCACSRResponse) Reset() {
	*x = CreateOrgCACSRResponse{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateOrgCACSRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateOrgCACSRResponse) ProtoMessage() {}

func (x *CreateOrgCACSRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateOrgCACSRResponse.ProtoReflect.Descriptor instead.
func (*CreateOrgCACSRResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{3}
}

func (x *CreateOrgCACSRResponse) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

type InstallOrgCARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	CertPem       string                 `protobuf:"bytes,2,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	ChainPem      string                 `protobuf:"bytes,3,opt,name=chain_pem,json=chainPem,proto3" json:"chain_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *InstallOrgCARequest) Reset() {
	*x = InstallOrgCARequest{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *InstallOrgCARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*InstallOrgCARequest) ProtoMessage() {}

func (x *InstallOrgCARequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use InstallOrgCARequest.ProtoReflect.Descriptor instead.
func (*InstallOrgCARequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{4}
}

func (x *InstallOrgCARequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *InstallOrgCARequest) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *InstallOrgCARequest) GetChainPem() string {
	if x != nil {
		return x.ChainPem
	}
	return ""
}

type CreateEnvCARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	EnvId         string                 `protobuf:"bytes,2,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	Name          string                 `protobuf:"bytes,3,opt,name=name,proto3" json:"name,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnvCARequest) Reset() {
	*x = CreateEnvCARequest{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnvCARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnvCARequest) ProtoMessage() {}

func (x *CreateEnvCARequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnvCARequest.ProtoReflect.Descriptor instead.
func (*CreateEnvCARequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{5}
}

func (x *CreateEnvCARequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *CreateEnvCARequest) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

func (x *CreateEnvCARequest) GetName() string {
	if x != nil {
		return x.Name
	}
	return ""
}

type CreateEnvCAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertPem       string                 `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	SerialHex     string                 `protobuf:"bytes,2,opt,name=serial_hex,json=serialHex,proto3" json:"serial_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateEnvCAResponse) Reset() {
	*x = CreateEnvCAResponse{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateEnvCAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateEnvCAResponse) ProtoMessage() {}

func (x *CreateEnvCAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateEnvCAResponse.ProtoReflect.Descriptor instead.
func (*CreateEnvCAResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{6}
}

func (x *CreateEnvCAResponse) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *CreateEnvCAResponse) GetSerialHex() string {
	if x != nil {
		return x.SerialHex
	}
	return ""
}

type IssueMemberCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	MemberEmail   string                 `protobuf:"bytes,2,opt,name=member_email,json=memberEmail,proto3" json:"member_email,omitempty"`
	OrgId         string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueMemberCertRequest) Reset() {
	*x = IssueMemberCertRequest{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueMemberCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueMemberCertRequest) ProtoMessage() {}

func (x *IssueMemberCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueMemberCertRequest.ProtoReflect.Descriptor instead.
func (*IssueMemberCertRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{7}
}

func (x *IssueMemberCertRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *IssueMemberCertRequest) GetMemberEmail() string {
	if x != nil {
		return x.MemberEmail
	}
	return ""
}

func (x *IssueMemberCertRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *IssueMemberCertRequest) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

type IssueMemberCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertPem       string                 `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	KeyPem        string                 `protobuf:"bytes,2,opt,name=key_pem,json=keyPem,proto3" json:"key_pem,omitempty"`
	SerialHex     string                 `protobuf:"bytes,3,opt,name=serial_hex,json=serialHex,proto3" json:"serial_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueMemberCertResponse) Reset() {
	*x = IssueMemberCertResponse{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueMemberCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueMemberCertResponse) ProtoMessage() {}

func (x *IssueMemberCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueMemberCertResponse.ProtoReflect.Descriptor instead.
func (*IssueMemberCertResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{8}
}

func (x *IssueMemberCertResponse) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *IssueMemberCertResponse) GetKeyPem() string {
	if x != nil {
		return x.KeyPem
	}
	return ""
}

func (x *IssueMemberCertResponse) GetSerialHex() string {
	if x != nil {
		return x.SerialHex
	}
	return ""
}

type IssueLeafCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	CommonName    string                 `protobuf:"bytes,2,opt,name=common_name,json=commonName,proto3" json:"common_name,omitempty"`
	DnsSans       []string               `protobuf:"bytes,3,rep,name=dns_sans,json=dnsSans,proto3" json:"dns_sans,omitempty"`
	TtlDays       int32                  `protobuf:"varint,4,opt,name=ttl_days,json=ttlDays,proto3" json:"ttl_days,omitempty"`
	KeyAlgorithm  string                 `protobuf:"bytes,5,opt,name=key_algorithm,json=keyAlgorithm,proto3" json:"key_algorithm,omitempty"` // RSA_2048 | ECDSA_P256
	EnvId         string                 `protobuf:"bytes,6,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueLeafCertRequest) Reset() {
	*x = IssueLeafCertRequest{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueLeafCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueLeafCertRequest) ProtoMessage() {}

func (x *IssueLeafCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueLeafCertRequest.ProtoReflect.Descriptor instead.
func (*IssueLeafCertRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{9}
}

func (x *IssueLeafCertRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *IssueLeafCertRequest) GetCommonName() string {
	if x != nil {
		return x.CommonName
	}
	return ""
}

func (x *IssueLeafCertRequest) GetDnsSans() []string {
	if x != nil {
		return x.DnsSans
	}
	return nil
}

func (x *IssueLeafCertRequest) GetTtlDays() int32 {
	if x != nil {
		return x.TtlDays
	}
	return 0
}

func (x *IssueLeafCertRequest) GetKeyAlgorithm() string {
	if x != nil {
		return x.KeyAlgorithm
	}
	return ""
}

func (x *IssueLeafCertRequest) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

type IssueLeafCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertPem       string                 `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	KeyPem        string                 `protobuf:"bytes,2,opt,name=key_pem,json=keyPem,proto3" json:"key_pem,omitempty"`
	SerialHex     string                 `protobuf:"bytes,3,opt,name=serial_hex,json=serialHex,proto3" json:"serial_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueLeafCertResponse) Reset() {
	*x = IssueLeafCertResponse{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueLeafCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueLeafCertResponse) ProtoMessage() {}

func (x *IssueLeafCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueLeafCertResponse.ProtoReflect.Descriptor instead.
func (*IssueLeafCertResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{10}
}

func (x *IssueLeafCertResponse) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *IssueLeafCertResponse) GetKeyPem() string {
	if x != nil {
		return x.KeyPem
	}
	return ""
}

func (x *IssueLeafCertResponse) GetSerialHex() string {
	if x != nil {
		return x.SerialHex
	}
	return ""
}

type SignCSRRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	CsrPem        string                 `protobuf:"bytes,2,opt,name=csr_pem,json=csrPem,proto3" json:"csr_pem,omitempty"`
	TtlDays       int32                  `protobuf:"varint,3,opt,name=ttl_days,json=ttlDays,proto3" json:"ttl_days,omitempty"`
	EnvId         string                 `protobuf:"bytes,4,opt,name=env_id,json=envId,proto3" json:"env_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignCSRRequest) Reset() {
	*x = SignCSRRequest{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignCSRRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCSRRequest) ProtoMessage() {}

func (x *SignCSRRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCSRRequest.ProtoReflect.Descriptor instead.
func (*SignCSRRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{11}
}

func (x *SignCSRRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *SignCSRRequest) GetCsrPem() string {
	if x != nil {
		return x.CsrPem
	}
	return ""
}

func (x *SignCSRRequest) GetTtlDays() int32 {
	if x != nil {
		return x.TtlDays
	}
	return 0
}

func (x *SignCSRRequest) GetEnvId() string {
	if x != nil {
		return x.EnvId
	}
	return ""
}

type SignCSRResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertPem       string                 `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	SerialHex     string                 `protobuf:"bytes,2,opt,name=serial_hex,json=serialHex,proto3" json:"serial_hex,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SignCSRResponse) Reset() {
	*x = SignCSRResponse{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SignCSRResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SignCSRResponse) ProtoMessage() {}

func (x *SignCSRResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SignCSRResponse.ProtoReflect.Descriptor instead.
func (*SignCSRResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{12}
}

func (x *SignCSRResponse) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *SignCSRResponse) GetSerialHex() string {
	if x != nil {
		return x.SerialHex
	}
	return ""
}

type RevokeCertRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerialHex     string                 `protobuf:"bytes,1,opt,name=serial_hex,json=serialHex,proto3" json:"serial_hex,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Reason        int32                  `protobuf:"varint,3,opt,name=reason,proto3" json:"reason,omitempty"` // RFC 5280 reason code
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCertRequest) Reset() {
	*x = RevokeCertRequest{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCertRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCertRequest) ProtoMessage() {}

func (x *RevokeCertRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCertRequest.ProtoReflect.Descriptor instead.
func (*RevokeCertRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{13}
}

func (x *RevokeCertRequest) GetSerialHex() string {
	if x != nil {
		return x.SerialHex
	}
	return ""
}

func (x *RevokeCertRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *RevokeCertRequest) GetReason() int32 {
	if x != nil {
		return x.Reason
	}
	return 0
}

type RevokeCertResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeCertResponse) Reset() {
	*x = RevokeCertResponse{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeCertResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeCertResponse) ProtoMessage() {}

func (x *RevokeCertResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeCertResponse.ProtoReflect.Descriptor instead.
func (*RevokeCertResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{14}
}

func (x *RevokeCertResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type GetCRLRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	DeltaOnly     bool                   `protobuf:"varint,2,opt,name=delta_only,json=deltaOnly,proto3" json:"delta_only,omitempty"` // If true, return only delta CRL
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCRLRequest) Reset() {
	*x = GetCRLRequest{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[15]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCRLRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCRLRequest) ProtoMessage() {}

func (x *GetCRLRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[15]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCRLRequest.ProtoReflect.Descriptor instead.
func (*GetCRLRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{15}
}

func (x *GetCRLRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *GetCRLRequest) GetDeltaOnly() bool {
	if x != nil {
		return x.DeltaOnly
	}
	return false
}

type GetCRLResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CrlDer        []byte                 `protobuf:"bytes,1,opt,name=crl_der,json=crlDer,proto3" json:"crl_der,omitempty"`
	CrlNumber     int64                  `protobuf:"varint,2,opt,name=crl_number,json=crlNumber,proto3" json:"crl_number,omitempty"`
	IsDelta       bool                   `protobuf:"varint,3,opt,name=is_delta,json=isDelta,proto3" json:"is_delta,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetCRLResponse) Reset() {
	*x = GetCRLResponse{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[16]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetCRLResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetCRLResponse) ProtoMessage() {}

func (x *GetCRLResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[16]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetCRLResponse.ProtoReflect.Descriptor instead.
func (*GetCRLResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{16}
}

func (x *GetCRLResponse) GetCrlDer() []byte {
	if x != nil {
		return x.CrlDer
	}
	return nil
}

func (x *GetCRLResponse) GetCrlNumber() int64 {
	if x != nil {
		return x.CrlNumber
	}
	return 0
}

func (x *GetCRLResponse) GetIsDelta() bool {
	if x != nil {
		return x.IsDelta
	}
	return false
}

type CheckOCSPRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SerialHex     string                 `protobuf:"bytes,1,opt,name=serial_hex,json=serialHex,proto3" json:"serial_hex,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOCSPRequest) Reset() {
	*x = CheckOCSPRequest{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[17]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOCSPRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOCSPRequest) ProtoMessage() {}

func (x *CheckOCSPRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[17]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOCSPRequest.ProtoReflect.Descriptor instead.
func (*CheckOCSPRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{17}
}

func (x *CheckOCSPRequest) GetSerialHex() string {
	if x != nil {
		return x.SerialHex
	}
	return ""
}

func (x *CheckOCSPRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type CheckOCSPResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Status        int32                  `protobuf:"varint,1,opt,name=status,proto3" json:"status,omitempty"`                       // 0=good, 1=revoked, 2=unknown
	RevokedAt     string                 `protobuf:"bytes,2,opt,name=revoked_at,json=revokedAt,proto3" json:"revoked_at,omitempty"` // RFC3339, empty if not revoked
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CheckOCSPResponse) Reset() {
	*x = CheckOCSPResponse{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[18]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CheckOCSPResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CheckOCSPResponse) ProtoMessage() {}

func (x *CheckOCSPResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[18]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CheckOCSPResponse.ProtoReflect.Descriptor instead.
func (*CheckOCSPResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{18}
}

func (x *CheckOCSPResponse) GetStatus() int32 {
	if x != nil {
		return x.Status
	}
	return 0
}

func (x *CheckOCSPResponse) GetRevokedAt() string {
	if x != nil {
		return x.RevokedAt
	}
	return ""
}

type GetRootCARequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRootCARequest) Reset() {
	*x = GetRootCARequest{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[19]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRootCARequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRootCARequest) ProtoMessage() {}

func (x *GetRootCARequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[19]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRootCARequest.ProtoReflect.Descriptor instead.
func (*GetRootCARequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{19}
}

type GetRootCAResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertPem       string                 `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *GetRootCAResponse) Reset() {
	*x = GetRootCAResponse{}
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[20]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetRootCAResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetRootCAResponse) ProtoMessage() {}

func (x *GetRootCAResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_pki_proto_msgTypes[20]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetRootCAResponse.ProtoReflect.Descriptor instead.
func (*GetRootCAResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_pki_proto_rawDescGZIP(), []int{20}
}

func (x *GetRootCAResponse) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

var File_api_proto_minikms_v1_pki_proto protoreflect.FileDescriptor

const file_api_proto_minikms_v1_pki_proto_rawDesc = "" +
	"\n" +
	"\x1eapi/proto/minikms/v1/pki.proto\x12\n" +
	"minikms.v1\"F\n" +
	"\x12CreateOrgCARequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\borg_name\x18\x02 \x01(\tR\aorgName\"O\n" +
	"\x13CreateOrgCAResponse\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\tR\acertPem\x12\x1d\n" +
	"\n" +
	"serial_hex\x18\x02 \x01(\tR\tserialHex\"I\n" +
	"\x15CreateOrgCACSRRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\borg_name\x18\x02 \x01(\tR\aorgName\"1\n" +
	"\x16CreateOrgCACSRResponse\x12\x17\n" +
	"\acsr_pem\x18\x01 \x01(\tR\x06csrPem\"d\n" +
	"\x13InstallOrgCARequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\bcert_pem\x18\x02 \x01(\tR\acertPem\x12\x1b\n" +
	"\tchain_pem\x18\x03 \x01(\tR\bchainPem\"V\n" +
	"\x12CreateEnvCARequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x15\n" +
	"\x06env_id\x18\x02 \x01(\tR\x05envId\x12\x12\n" +
	"\x04name\x18\x03 \x01(\tR\x04name\"O\n" +
	"\x13CreateEnvCAResponse\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\tR\acertPem\x12\x1d\n" +
	"\n" +
	"serial_hex\x18\x02 \x01(\tR\tserialHex\"\x83\x01\n" +
	"\x16IssueMemberCertRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12!\n" +
	"\fmember_email\x18\x02 \x01(\tR\vmemberEmail\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\"l\n" +
	"\x17IssueMemberCertResponse\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\tR\acertPem\x12\x17\n" +
	"\akey_pem\x18\x02 \x01(\tR\x06keyPem\x12\x1d\n" +
	"\n" +
	"serial_hex\x18\x03 \x01(\tR\tserialHex\"\xc0\x01\n" +
	"\x14IssueLeafCertRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x1f\n" +
	"\vcommon_name\x18\x02 \x01(\tR\n" +
	"commonName\x12\x19\n" +
	"\bdns_sans\x18\x03 \x03(\tR\adnsSans\x12\x19\n" +
	"\bttl_days\x18\x04 \x01(\x05R\attlDays\x12#\n" +
	"\rkey_algorithm\x18\x05 \x01(\tR\fkeyAlgorithm\x12\x15\n" +
	"\x06env_id\x18\x06 \x01(\tR\x05envId\"j\n" +
	"\x15IssueLeafCertResponse\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\tR\acertPem\x12\x17\n" +
	"\akey_pem\x18\x02 \x01(\tR\x06keyPem\x12\x1d\n" +
	"\n" +
	"serial_hex\x18\x03 \x01(\tR\tserialHex\"r\n" +
	"\x0eSignCSRRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x17\n" +
	"\acsr_pem\x18\x02 \x01(\tR\x06csrPem\x12\x19\n" +
	"\bttl_days\x18\x03 \x01(\x05R\attlDays\x12\x15\n" +
	"\x06env_id\x18\x04 \x01(\tR\x05envId\"K\n" +
	"\x0fSignCSRResponse\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\tR\acertPem\x12\x1d\n" +
	"\n" +
	"serial_hex\x18\x02 \x01(\tR\tserialHex\"a\n" +
	"\x11RevokeCertRequest\x12\x1d\n" +
	"\n" +
	"serial_hex\x18\x01 \x01(\tR\tserialHex\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x16\n" +
	"\x06reason\x18\x03 \x01(\x05R\x06reason\".\n" +
	"\x12RevokeCertResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"E\n" +
	"\rGetCRLRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x1d\n" +
	"\n" +
	"delta_only\x18\x02 \x01(\bR\tdeltaOnly\"c\n" +
	"\x0eGetCRLResponse\x12\x17\n" +
	"\acrl_der\x18\x01 \x01(\fR\x06crlDer\x12\x1d\n" +
	"\n" +
	"crl_number\x18\x02 \x01(\x03R\tcrlNumber\x12\x19\n" +
	"\bis_delta\x18\x03 \x01(\bR\aisDelta\"H\n" +
	"\x10CheckOCSPRequest\x12\x1d\n" +
	"\n" +
	"serial_hex\x18\x01 \x01(\tR\tserialHex\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\"J\n" +
	"\x11CheckOCSPResponse\x12\x16\n" +
	"\x06status\x18\x01 \x01(\x05R\x06status\x12\x1d\n" +
	"\n" +
	"revoked_at\x18\x02 \x01(\tR\trevokedAt\"\x12\n" +
	"\x10GetRootCARequest\".\n" +
	"\x11GetRootCAResponse\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\tR\acertPem2\xef\x06\n" +
	"\n" +
	"PKIService\x12N\n" +
	"\vCreateOrgCA\x12\x1e.minikms.v1.CreateOrgCARequest\x1a\x1f.minikms.v1.CreateOrgCAResponse\x12W\n" +
	"\x0eCreateOrgCACSR\x12!.minikms.v1.CreateOrgCACSRRequest\x1a\".minikms.v1.CreateOrgCACSRResponse\x12P\n" +
	"\fInstallOrgCA\x12\x1f.minikms.v1.InstallOrgCARequest\x1a\x1f.minikms.v1.CreateOrgCAResponse\x12N\n" +
	"\vCreateEnvCA\x12\x1e.minikms.v1.CreateEnvCARequest\x1a\x1f.minikms.v1.CreateEnvCAResponse\x12Z\n" +
	"\x0fIssueMemberCert\x12\".minikms.v1.IssueMemberCertRequest\x1a#.minikms.v1.IssueMemberCertResponse\x12T\n" +
	"\rIssueLeafCert\x12 .minikms.v1.IssueLeafCertRequest\x1a!.minikms.v1.IssueLeafCertResponse\x12B\n" +
	"\aSignCSR\x12\x1a.minikms.v1.SignCSRRequest\x1a\x1b.minikms.v1.SignCSRResponse\x12K\n" +
	"\n" +
	"RevokeCert\x12\x1d.minikms.v1.RevokeCertRequest\x1a\x1e.minikms.v1.RevokeCertResponse\x12?\n" +
	"\x06GetCRL\x12\x19.minikms.v1.GetCRLRequest\x1a\x1a.minikms.v1.GetCRLResponse\x12H\n" +
	"\tCheckOCSP\x12\x1c.minikms.v1.CheckOCSPRequest\x1a\x1d.minikms.v1.CheckOCSPResponse\x12H\n" +
	"\tGetRootCA\x12\x1c.minikms.v1.GetRootCARequest\x1a\x1d.minikms.v1.GetRootCAResponseBAZ?github.com/envsync-cloud/minikms/api/proto/minikms/v1;minikmsv1b\x06proto3"

var (
	file_api_proto_minikms_v1_pki_proto_rawDescOnce sync.Once
	file_api_proto_minikms_v1_pki_proto_rawDescData []byte
)

func file_api_proto_minikms_v1_pki_proto_rawDescGZIP() []byte {
	file_api_proto_minikms_v1_pki_proto_rawDescOnce.Do(func() {
		file_api_proto_minikms_v1_pki_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_minikms_v1_pki_proto_rawDesc), len(file_api_proto_minikms_v1_pki_proto_rawDesc)))
	})
	return file_api_proto_minikms_v1_pki_proto_rawDescData
}

var file_api_proto_minikms_v1_pki_proto_msgTypes = make([]protoimpl.MessageInfo, 21)
var file_api_proto_minikms_v1_pki_proto_goTypes = []any{
	(*CreateOrgCARequest)(nil),      // 0: minikms.v1.CreateOrgCARequest
	(*CreateOrgCAResponse)(nil),     // 1: minikms.v1.CreateOrgCAResponse
	(*CreateOrgCACSRRequest)(nil),   // 2: minikms.v1.CreateOrgCACSRRequest
	(*CreateOrgCACSRResponse)(nil),  // 3: minikms.v1.CreateOrgCACSRResponse
	(*InstallOrgCARequest)(nil),     // 4: minikms.v1.InstallOrgCARequest
	(*CreateEnvCARequest)(nil),      // 5: minikms.v1.CreateEnvCARequest
	(*CreateEnvCAResponse)(nil),     // 6: minikms.v1.CreateEnvCAResponse
	(*IssueMemberCertRequest)(nil),  // 7: minikms.v1.IssueMemberCertRequest
	(*IssueMemberCertResponse)(nil), // 8: minikms.v1.IssueMemberCertResponse
	(*IssueLeafCertRequest)(nil),    // 9: minikms.v1.IssueLeafCertRequest
	(*IssueLeafCertResponse)(nil),   // 10: minikms.v1.IssueLeafCertResponse
	(*SignCSRRequest)(nil),          // 11: minikms.v1.SignCSRRequest
	(*SignCSRResponse)(nil),         // 12: minikms.v1.SignCSRResponse
	(*RevokeCertRequest)(nil),       // 13: minikms.v1.RevokeCertRequest
	(*RevokeCertResponse)(nil),      // 14: minikms.v1.RevokeCertResponse
	(*GetCRLRequest)(nil),           // 15: minikms.v1.GetCRLRequest
	(*GetCRLResponse)(nil),          // 16: minikms.v1.GetCRLResponse
	(*CheckOCSPRequest)(nil),        // 17: minikms.v1.CheckOCSPRequest
	(*CheckOCSPResponse)(nil),       // 18: minikms.v1.CheckOCSPResponse
	(*GetRootCARequest)(nil),        // 19: minikms.v1.GetRootCARequest
	(*GetRootCAResponse)(nil),       // 20: minikms.v1.GetRootCAResponse
}
var file_api_proto_minikms_v1_pki_proto_depIdxs = []int32{
	0,  // 0: minikms.v1.PKIService.CreateOrgCA:input_type -> minikms.v1.CreateOrgCARequest
	2,  // 1: minikms.v1.PKIService.CreateOrgCACSR:input_type -> minikms.v1.CreateOrgCACSRRequest
	4,  // 2: minikms.v1.PKIService.InstallOrgCA:input_type -> minikms.v1.InstallOrgCARequest
	5,  // 3: minikms.v1.PKIService.CreateEnvCA:input_type -> minikms.v1.CreateEnvCARequest
	7,  // 4: minikms.v1.PKIService.IssueMemberCert:input_type -> minikms.v1.IssueMemberCertRequest
	9,  // 5: minikms.v1.PKIService.IssueLeafCert:input_type -> minikms.v1.IssueLeafCertRequest
	11, // 6: minikms.v1.PKIService.SignCSR:input_type -> minikms.v1.SignCSRRequest
	13, // 7: minikms.v1.PKIService.RevokeCert:input_type -> minikms.v1.RevokeCertRequest
	15, // 8: minikms.v1.PKIService.GetCRL:input_type -> minikms.v1.GetCRLRequest
	17, // 9: minikms.v1.PKIService.CheckOCSP:input_type -> minikms.v1.CheckOCSPRequest
	19, // 10: minikms.v1.PKIService.GetRootCA:input_type -> minikms.v1.GetRootCARequest
	1,  // 11: minikms.v1.PKIService.CreateOrgCA:output_type -> minikms.v1.CreateOrgCAResponse
	3,  // 12: minikms.v1.PKIService.CreateOrgCACSR:output_type -> minikms.v1.CreateOrgCACSRResponse
	1,  // 13: minikms.v1.PKIService.InstallOrgCA:output_type -> minikms.v1.CreateOrgCAResponse
	6,  // 14: minikms.v1.PKIService.CreateEnvCA:output_type -> minikms.v1.CreateEnvCAResponse
	8,  // 15: minikms.v1.PKIService.IssueMemberCert:output_type -> minikms.v1.IssueMemberCertResponse
	10, // 16: minikms.v1.PKIService.IssueLeafCert:output_type -> minikms.v1.IssueLeafCertResponse
	12, // 17: minikms.v1.PKIService.SignCSR:output_type -> minikms.v1.SignCSRResponse
	14, // 18: minikms.v1.PKIService.RevokeCert:output_type -> minikms.v1.RevokeCertResponse
	16, // 19: minikms.v1.PKIService.GetCRL:output_type -> minikms.v1.GetCRLResponse
	18, // 20: minikms.v1.PKIService.CheckOCSP:output_type -> minikms.v1.CheckOCSPResponse
	20, // 21: minikms.v1.PKIService.GetRootCA:output_type -> minikms.v1.GetRootCAResponse
	11, // [11:22] is the sub-list for method output_type
	0,  // [0:11] is the sub-list for method input_type
	0,  // [0:0] is the sub-list for extension type_name
	0,  // [0:0] is the sub-list for extension extendee
	0,  // [0:0] is the sub-list for field type_name
}

func init() { file_api_proto_minikms_v1_pki_proto_init() }
func file_api_proto_minikms_v1_pki_proto_init() {
	if File_api_proto_minikms_v1_pki_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_minikms_v1_pki_proto_rawDesc), len(file_api_proto_minikms_v1_pki_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   21,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_minikms_v1_pki_proto_goTypes,
		DependencyIndexes: file_api_proto_minikms_v1_pki_proto_depIdxs,
		MessageInfos:      file_api_proto_minikms_v1_pki_proto_msgTypes,
	}.Build()
	File_api_proto_minikms_v1_pki_proto = out.File
	file_api_proto_minikms_v1_pki_proto_goTypes = nil
	file_api_proto_minikms_v1_pki_proto_depIdxs = nil
}
