// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/proto/minikms/v1/pki.proto

package minikmsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	PKIService_CreateOrgCA_FullMethodName     = "/minikms.v1.PKIService/CreateOrgCA"
	PKIService_IssueMemberCert_FullMethodName = "/minikms.v1.PKIService/IssueMemberCert"
	PKIService_RevokeCert_FullMethodName      = "/minikms.v1.PKIService/RevokeCert"
	PKIService_GetCRL_FullMethodName          = "/minikms.v1.PKIService/GetCRL"
	PKIService_CheckOCSP_FullMethodName       = "/minikms.v1.PKIService/CheckOCSP"
	PKIService_GetRootCA_FullMethodName       = "/minikms.v1.PKIService/GetRootCA"
)

// PKIServiceClient is the client API for PKIService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// PKIService manages the 3-level PKI hierarchy:
// Root CA -> Org Intermediate CA (IsCA:true, MaxPathLen:0) -> Member Certificate (IsCA:false)
type PKIServiceClient interface {
	CreateOrgCA(ctx context.Context, in *CreateOrgCARequest, opts ...grpc.CallOption) (*CreateOrgCAResponse, error)
	IssueMemberCert(ctx context.Context, in *IssueMemberCertRequest, opts ...grpc.CallOption) (*IssueMemberCertResponse, error)
	RevokeCert(ctx context.Context, in *RevokeCertRequest, opts ...grpc.CallOption) (*RevokeCertResponse, error)
	GetCRL(ctx context.Context, in *GetCRLRequest, opts ...grpc.CallOption) (*GetCRLResponse, error)
	CheckOCSP(ctx context.Context, in *CheckOCSPRequest, opts ...grpc.CallOption) (*CheckOCSPResponse, error)
	GetRootCA(ctx context.Context, in *GetRootCARequest, opts ...grpc.CallOption) (*GetRootCAResponse, error)
}

type pKIServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewPKIServiceClient(cc grpc.ClientConnInterface) PKIServiceClient {
	return &pKIServiceClient{cc}
}

func (c *pKIServiceClient) CreateOrgCA(ctx context.Context, in *CreateOrgCARequest, opts ...grpc.CallOption) (*CreateOrgCAResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CreateOrgCAResponse)
	err := c.cc.Invoke(ctx, PKIService_CreateOrgCA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) IssueMemberCert(ctx context.Context, in *IssueMemberCertRequest, opts ...grpc.CallOption) (*IssueMemberCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(IssueMemberCertResponse)
	err := c.cc.Invoke(ctx, PKIService_IssueMemberCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) RevokeCert(ctx context.Context, in *RevokeCertRequest, opts ...grpc.CallOption) (*RevokeCertResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(RevokeCertResponse)
	err := c.cc.Invoke(ctx, PKIService_RevokeCert_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) GetCRL(ctx context.Context, in *GetCRLRequest, opts ...grpc.CallOption) (*GetCRLResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetCRLResponse)
	err := c.cc.Invoke(ctx, PKIService_GetCRL_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) CheckOCSP(ctx context.Context, in *CheckOCSPRequest, opts ...grpc.CallOption) (*CheckOCSPResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(CheckOCSPResponse)
	err := c.cc.Invoke(ctx, PKIService_CheckOCSP_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *pKIServiceClient) GetRootCA(ctx context.Context, in *GetRootCARequest, opts ...grpc.CallOption) (*GetRootCAResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(GetRootCAResponse)
	err := c.cc.Invoke(ctx, PKIService_GetRootCA_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// PKIServiceServer is the server API for PKIService service.
// All implementations must embed UnimplementedPKIServiceServer
// for forward compatibility.
//
// PKIService manages the 3-level PKI hierarchy:
// Root CA -> Org Intermediate CA (IsCA:true, MaxPathLen:0) -> Member Certificate (IsCA:false)
type PKIServiceServer interface {
	CreateOrgCA(context.Context, *CreateOrgCARequest) (*CreateOrgCAResponse, error)
	IssueMemberCert(context.Context, *IssueMemberCertRequest) (*IssueMemberCertResponse, error)
	RevokeCert(context.Context, *RevokeCertRequest) (*RevokeCertResponse, error)
	GetCRL(context.Context, *GetCRLRequest) (*GetCRLResponse, error)
	CheckOCSP(context.Context, *CheckOCSPRequest) (*CheckOCSPResponse, error)
	GetRootCA(context.Context, *GetRootCARequest) (*GetRootCAResponse, error)
	mustEmbedUnimplementedPKIServiceServer()
}

// UnimplementedPKIServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedPKIServiceServer struct{}

func (UnimplementedPKIServiceServer) CreateOrgCA(context.Context, *CreateOrgCARequest) (*CreateOrgCAResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CreateOrgCA not implemented")
}
func (UnimplementedPKIServiceServer) IssueMemberCert(context.Context, *IssueMemberCertRequest) (*IssueMemberCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method IssueMemberCert not implemented")
}
func (UnimplementedPKIServiceServer) RevokeCert(context.Context, *RevokeCertRequest) (*RevokeCertResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method RevokeCert not implemented")
}
func (UnimplementedPKIServiceServer) GetCRL(context.Context, *GetCRLRequest) (*GetCRLResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetCRL not implemented")
}
func (UnimplementedPKIServiceServer) CheckOCSP(context.Context, *CheckOCSPRequest) (*CheckOCSPResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method CheckOCSP not implemented")
}
func (UnimplementedPKIServiceServer) GetRootCA(context.Context, *GetRootCARequest) (*GetRootCAResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method GetRootCA not implemented")
}
func (UnimplementedPKIServiceServer) mustEmbedUnimplementedPKIServiceServer() {}
func (UnimplementedPKIServiceServer) testEmbeddedByValue()                    {}

// UnsafePKIServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to PKIServiceServer will
// result in compilation errors.
type UnsafePKIServiceServer interface {
	mustEmbedUnimplementedPKIServiceServer()
}

func RegisterPKIServiceServer(s grpc.ServiceRegistrar, srv PKIServiceServer) {
	// If the following call panics, it indicates UnimplementedPKIServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&PKIService_ServiceDesc, srv)
}

func _PKIService_CreateOrgCA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CreateOrgCARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).CreateOrgCA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_CreateOrgCA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).CreateOrgCA(ctx, req.(*CreateOrgCARequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_IssueMemberCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(IssueMemberCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).IssueMemberCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_IssueMemberCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).IssueMemberCert(ctx, req.(*IssueMemberCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_RevokeCert_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(RevokeCertRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).RevokeCert(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_RevokeCert_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).RevokeCert(ctx, req.(*RevokeCertRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_GetCRL_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetCRLRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).GetCRL(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_GetCRL_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).GetCRL(ctx, req.(*GetCRLRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_CheckOCSP_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(CheckOCSPRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).CheckOCSP(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_CheckOCSP_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).CheckOCSP(ctx, req.(*CheckOCSPRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _PKIService_GetRootCA_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(GetRootCARequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(PKIServiceServer).GetRootCA(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: PKIService_GetRootCA_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(PKIServiceServer).GetRootCA(ctx, req.(*GetRootCARequest))
	}
	return interceptor(ctx, in, info, handler)
}

// PKIService_ServiceDesc is the grpc.ServiceDesc for PKIService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var PKIService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "minikms.v1.PKIService",
	HandlerType: (*PKIServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "CreateOrgCA",
			Handler:    _PKIService_CreateOrgCA_Handler,
		},
		{
			MethodName: "IssueMemberCert",
			Handler:    _PKIService_IssueMemberCert_Handler,
		},
		{
			MethodName: "RevokeCert",
			Handler:    _PKIService_RevokeCert_Handler,
		},
		{
			MethodName: "GetCRL",
			Handler:    _PKIService_GetCRL_Handler,
		},
		{
			MethodName: "CheckOCSP",
			Handler:    _PKIService_CheckOCSP_Handler,
		},
		{
			MethodName: "GetRootCA",
			Handler:    _PKIService_GetRootCA_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/minikms/v1/pki.proto",
}
