// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v7.35.1
// source: api/proto/minikms/v1/session.proto

package minikmsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type IssueSessionChallengeRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertSerial    string                 `protobuf:"bytes,1,opt,name=cert_serial,json=certSerial,proto3" json:"cert_serial,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueSessionChallengeRequest) Reset() {
	*x = IssueSessionChallengeRequest{}
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueSessionChallengeRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueSessionChallengeRequest) ProtoMessage() {}

func (x *IssueSessionChallengeRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueSessionChallengeRequest.ProtoReflect.Descriptor instead.
func (*IssueSessionChallengeRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_session_proto_rawDescGZIP(), []int{0}
}

func (x *IssueSessionChallengeRequest) GetCertSerial() string {
	if x != nil {
		return x.CertSerial
	}
	return ""
}

type IssueSessionChallengeResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Nonce         []byte                 `protobuf:"bytes,1,opt,name=nonce,proto3" json:"nonce,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *IssueSessionChallengeResponse) Reset() {
	*x = IssueSessionChallengeResponse{}
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *IssueSessionChallengeResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*IssueSessionChallengeResponse) ProtoMessage() {}

func (x *IssueSessionChallengeResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use IssueSessionChallengeResponse.ProtoReflect.Descriptor instead.
func (*IssueSessionChallengeResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_session_proto_rawDescGZIP(), []int{1}
}

func (x *IssueSessionChallengeResponse) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

func (x *IssueSessionChallengeResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type CreateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertAuth      *CertAuth              `protobuf:"bytes,1,opt,name=cert_auth,json=certAuth,proto3" json:"cert_auth,omitempty"`
	Scopes        []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionRequest) Reset() {
	*x = CreateSessionRequest{}
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionRequest) ProtoMessage() {}

func (x *CreateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionRequest.ProtoReflect.Descriptor instead.
func (*CreateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_session_proto_rawDescGZIP(), []int{2}
}

func (x *CreateSessionRequest) GetCertAuth() *CertAuth {
	if x != nil {
		return x.CertAuth
	}
	return nil
}

func (x *CreateSessionRequest) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

// Certificate-based authentication: sign a nonce from IssueSessionChallenge.
type CertAuth struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	CertPem       string                 `protobuf:"bytes,1,opt,name=cert_pem,json=certPem,proto3" json:"cert_pem,omitempty"`
	SignedNonce   []byte                 `protobuf:"bytes,2,opt,name=signed_nonce,json=signedNonce,proto3" json:"signed_nonce,omitempty"`
	Nonce         []byte                 `protobuf:"bytes,3,opt,name=nonce,proto3" json:"nonce,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CertAuth) Reset() {
	*x = CertAuth{}
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CertAuth) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CertAuth) ProtoMessage() {}

func (x *CertAuth) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CertAuth.ProtoReflect.Descriptor instead.
func (*CertAuth) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_session_proto_rawDescGZIP(), []int{3}
}

func (x *CertAuth) GetCertPem() string {
	if x != nil {
		return x.CertPem
	}
	return ""
}

func (x *CertAuth) GetSignedNonce() []byte {
	if x != nil {
		return x.SignedNonce
	}
	return nil
}

func (x *CertAuth) GetNonce() []byte {
	if x != nil {
		return x.Nonce
	}
	return nil
}

type CreateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"` // JWT session token
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,2,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Scopes        []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *CreateSessionResponse) Reset() {
	*x = CreateSessionResponse{}
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *CreateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*CreateSessionResponse) ProtoMessage() {}

func (x *CreateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use CreateSessionResponse.ProtoReflect.Descriptor instead.
func (*CreateSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_session_proto_rawDescGZIP(), []int{4}
}

func (x *CreateSessionResponse) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

func (x *CreateSessionResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *CreateSessionResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

type ValidateSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSessionRequest) Reset() {
	*x = ValidateSessionRequest{}
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionRequest) ProtoMessage() {}

func (x *ValidateSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSessionRequest.ProtoReflect.Descriptor instead.
func (*ValidateSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_session_proto_rawDescGZIP(), []int{5}
}

func (x *ValidateSessionRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type ValidateSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Valid         bool                   `protobuf:"varint,1,opt,name=valid,proto3" json:"valid,omitempty"`
	MemberId      string                 `protobuf:"bytes,2,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,3,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	Role          string                 `protobuf:"bytes,4,opt,name=role,proto3" json:"role,omitempty"`
	CertSerial    string                 `protobuf:"bytes,5,opt,name=cert_serial,json=certSerial,proto3" json:"cert_serial,omitempty"`
	Scopes        []string               `protobuf:"bytes,6,rep,name=scopes,proto3" json:"scopes,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,7,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ValidateSessionResponse) Reset() {
	*x = ValidateSessionResponse{}
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ValidateSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ValidateSessionResponse) ProtoMessage() {}

func (x *ValidateSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ValidateSessionResponse.ProtoReflect.Descriptor instead.
func (*ValidateSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_session_proto_rawDescGZIP(), []int{6}
}

func (x *ValidateSessionResponse) GetValid() bool {
	if x != nil {
		return x.Valid
	}
	return false
}

func (x *ValidateSessionResponse) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *ValidateSessionResponse) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *ValidateSessionResponse) GetRole() string {
	if x != nil {
		return x.Role
	}
	return ""
}

func (x *ValidateSessionResponse) GetCertSerial() string {
	if x != nil {
		return x.CertSerial
	}
	return ""
}

func (x *ValidateSessionResponse) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *ValidateSessionResponse) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

type RevokeSessionRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	SessionToken  string                 `protobuf:"bytes,1,opt,name=session_token,json=sessionToken,proto3" json:"session_token,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionRequest) Reset() {
	*x = RevokeSessionRequest{}
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionRequest) ProtoMessage() {}

func (x *RevokeSessionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionRequest.ProtoReflect.Descriptor instead.
func (*RevokeSessionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_session_proto_rawDescGZIP(), []int{7}
}

func (x *RevokeSessionRequest) GetSessionToken() string {
	if x != nil {
		return x.SessionToken
	}
	return ""
}

type RevokeSessionResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeSessionResponse) Reset() {
	*x = RevokeSessionResponse{}
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeSessionResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeSessionResponse) ProtoMessage() {}

func (x *RevokeSessionResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeSessionResponse.ProtoReflect.Descriptor instead.
func (*RevokeSessionResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_session_proto_rawDescGZIP(), []int{8}
}

func (x *RevokeSessionResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type RevokeMemberSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeMemberSessionsRequest) Reset() {
	*x = RevokeMemberSessionsRequest{}
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeMemberSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeMemberSessionsRequest) ProtoMessage() {}

func (x *RevokeMemberSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeMemberSessionsRequest.ProtoReflect.Descriptor instead.
func (*RevokeMemberSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_session_proto_rawDescGZIP(), []int{9}
}

func (x *RevokeMemberSessionsRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *RevokeMemberSessionsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type RevokeMemberSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	RevokedCount  int32                  `protobuf:"varint,1,opt,name=revoked_count,json=revokedCount,proto3" json:"revoked_count,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *RevokeMemberSessionsResponse) Reset() {
	*x = RevokeMemberSessionsResponse{}
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *RevokeMemberSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*RevokeMemberSessionsResponse) ProtoMessage() {}

func (x *RevokeMemberSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use RevokeMemberSessionsResponse.ProtoReflect.Descriptor instead.
func (*RevokeMemberSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_session_proto_rawDescGZIP(), []int{10}
}

func (x *RevokeMemberSessionsResponse) GetRevokedCount() int32 {
	if x != nil {
		return x.RevokedCount
	}
	return 0
}

type ListSessionsRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	MemberId      string                 `protobuf:"bytes,1,opt,name=member_id,json=memberId,proto3" json:"member_id,omitempty"`
	OrgId         string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsRequest) Reset() {
	*x = ListSessionsRequest{}
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsRequest) ProtoMessage() {}

func (x *ListSessionsRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsRequest.ProtoReflect.Descriptor instead.
func (*ListSessionsRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_session_proto_rawDescGZIP(), []int{11}
}

func (x *ListSessionsRequest) GetMemberId() string {
	if x != nil {
		return x.MemberId
	}
	return ""
}

func (x *ListSessionsRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

type ListSessionsResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Sessions      []*SessionInfo         `protobuf:"bytes,1,rep,name=sessions,proto3" json:"sessions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *ListSessionsResponse) Reset() {
	*x = ListSessionsResponse{}
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *ListSessionsResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*ListSessionsResponse) ProtoMessage() {}

func (x *ListSessionsResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use ListSessionsResponse.ProtoReflect.Descriptor instead.
func (*ListSessionsResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_session_proto_rawDescGZIP(), []int{12}
}

func (x *ListSessionsResponse) GetSessions() []*SessionInfo {
	if x != nil {
		return x.Sessions
	}
	return nil
}

type SessionInfo struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Jti           string                 `protobuf:"bytes,1,opt,name=jti,proto3" json:"jti,omitempty"`
	CertSerial    string                 `protobuf:"bytes,2,opt,name=cert_serial,json=certSerial,proto3" json:"cert_serial,omitempty"`
	Scopes        []string               `protobuf:"bytes,3,rep,name=scopes,proto3" json:"scopes,omitempty"`
	IssuedAt      *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=issued_at,json=issuedAt,proto3" json:"issued_at,omitempty"`
	ExpiresAt     *timestamppb.Timestamp `protobuf:"bytes,5,opt,name=expires_at,json=expiresAt,proto3" json:"expires_at,omitempty"`
	Revoked       bool                   `protobuf:"varint,6,opt,name=revoked,proto3" json:"revoked,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SessionInfo) Reset() {
	*x = SessionInfo{}
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SessionInfo) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SessionInfo) ProtoMessage() {}

func (x *SessionInfo) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_session_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SessionInfo.ProtoReflect.Descriptor instead.
func (*SessionInfo) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_session_proto_rawDescGZIP(), []int{13}
}

func (x *SessionInfo) GetJti() string {
	if x != nil {
		return x.Jti
	}
	return ""
}

func (x *SessionInfo) GetCertSerial() string {
	if x != nil {
		return x.CertSerial
	}
	return ""
}

func (x *SessionInfo) GetScopes() []string {
	if x != nil {
		return x.Scopes
	}
	return nil
}

func (x *SessionInfo) GetIssuedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.IssuedAt
	}
	return nil
}

func (x *SessionInfo) GetExpiresAt() *timestamppb.Timestamp {
	if x != nil {
		return x.ExpiresAt
	}
	return nil
}

func (x *SessionInfo) GetRevoked() bool {
	if x != nil {
		return x.Revoked
	}
	return false
}

var File_api_proto_minikms_v1_session_proto protoreflect.FileDescriptor

const file_api_proto_minikms_v1_session_proto_rawDesc = "" +
	"\n" +
	"\"api/proto/minikms/v1/session.proto\x12\n" +
	"minikms.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"?\n" +
	"\x1cIssueSessionChallengeRequest\x12\x1f\n" +
	"\vcert_serial\x18\x01 \x01(\tR\n" +
	"certSerial\"p\n" +
	"\x1dIssueSessionChallengeResponse\x12\x14\n" +
	"\x05nonce\x18\x01 \x01(\fR\x05nonce\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\"a\n" +
	"\x14CreateSessionRequest\x121\n" +
	"\tcert_auth\x18\x01 \x01(\v2\x14.minikms.v1.CertAuthR\bcertAuth\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\"^\n" +
	"\bCertAuth\x12\x19\n" +
	"\bcert_pem\x18\x01 \x01(\tR\acertPem\x12!\n" +
	"\fsigned_nonce\x18\x02 \x01(\fR\vsignedNonce\x12\x14\n" +
	"\x05nonce\x18\x03 \x01(\fR\x05nonce\"\x8f\x01\n" +
	"\x15CreateSessionResponse\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\x129\n" +
	"\n" +
	"expires_at\x18\x02 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\"=\n" +
	"\x16ValidateSessionRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\"\xeb\x01\n" +
	"\x17ValidateSessionResponse\x12\x14\n" +
	"\x05valid\x18\x01 \x01(\bR\x05valid\x12\x1b\n" +
	"\tmember_id\x18\x02 \x01(\tR\bmemberId\x12\x15\n" +
	"\x06org_id\x18\x03 \x01(\tR\x05orgId\x12\x12\n" +
	"\x04role\x18\x04 \x01(\tR\x04role\x12\x1f\n" +
	"\vcert_serial\x18\x05 \x01(\tR\n" +
	"certSerial\x12\x16\n" +
	"\x06scopes\x18\x06 \x03(\tR\x06scopes\x129\n" +
	"\n" +
	"expires_at\x18\a \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\";\n" +
	"\x14RevokeSessionRequest\x12#\n" +
	"\rsession_token\x18\x01 \x01(\tR\fsessionToken\"1\n" +
	"\x15RevokeSessionResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"Q\n" +
	"\x1bRevokeMemberSessionsRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\"C\n" +
	"\x1cRevokeMemberSessionsResponse\x12#\n" +
	"\rrevoked_count\x18\x01 \x01(\x05R\frevokedCount\"I\n" +
	"\x13ListSessionsRequest\x12\x1b\n" +
	"\tmember_id\x18\x01 \x01(\tR\bmemberId\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\"K\n" +
	"\x14ListSessionsResponse\x123\n" +
	"\bsessions\x18\x01 \x03(\v2\x17.minikms.v1.SessionInfoR\bsessions\"\xe6\x01\n" +
	"\vSessionInfo\x12\x10\n" +
	"\x03jti\x18\x01 \x01(\tR\x03jti\x12\x1f\n" +
	"\vcert_serial\x18\x02 \x01(\tR\n" +
	"certSerial\x12\x16\n" +
	"\x06scopes\x18\x03 \x03(\tR\x06scopes\x127\n" +
	"\tissued_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\bissuedAt\x129\n" +
	"\n" +
	"expires_at\x18\x05 \x01(\v2\x1a.google.protobuf.TimestampR\texpiresAt\x12\x18\n" +
	"\arevoked\x18\x06 \x01(\bR\arevoked2\xc4\x04\n" +
	"\x0eSessionService\x12l\n" +
	"\x15IssueSessionChallenge\x12(.minikms.v1.IssueSessionChallengeRequest\x1a).minikms.v1.IssueSessionChallengeResponse\x12T\n" +
	"\rCreateSession\x12 .minikms.v1.CreateSessionRequest\x1a!.minikms.v1.CreateSessionResponse\x12Z\n" +
	"\x0fValidateSession\x12\".minikms.v1.ValidateSessionRequest\x1a#.minikms.v1.ValidateSessionResponse\x12T\n" +
	"\rRevokeSession\x12 .minikms.v1.RevokeSessionRequest\x1a!.minikms.v1.RevokeSessionResponse\x12i\n" +
	"\x14RevokeMemberSessions\x12'.minikms.v1.RevokeMemberSessionsRequest\x1a(.minikms.v1.RevokeMemberSessionsResponse\x12Q\n" +
	"\fListSessions\x12\x1f.minikms.v1.ListSessionsRequest\x1a .minikms.v1.ListSessionsResponseBAZ?github.com/envsync-cloud/minikms/api/proto/minikms/v1;minikmsv1b\x06proto3"

var (
	file_api_proto_minikms_v1_session_proto_rawDescOnce sync.Once
	file_api_proto_minikms_v1_session_proto_rawDescData []byte
)

func file_api_proto_minikms_v1_session_proto_rawDescGZIP() []byte {
	file_api_proto_minikms_v1_session_proto_rawDescOnce.Do(func() {
		file_api_proto_minikms_v1_session_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_minikms_v1_session_proto_rawDesc), len(file_api_proto_minikms_v1_session_proto_rawDesc)))
	})
	return file_api_proto_minikms_v1_session_proto_rawDescData
}

var file_api_proto_minikms_v1_session_proto_msgTypes = make([]protoimpl.MessageInfo, 14)
var file_api_proto_minikms_v1_session_proto_goTypes = []any{
	(*IssueSessionChallengeRequest)(nil),  // 0: minikms.v1.IssueSessionChallengeRequest
	(*IssueSessionChallengeResponse)(nil), // 1: minikms.v1.IssueSessionChallengeResponse
	(*CreateSessionRequest)(nil),          // 2: minikms.v1.CreateSessionRequest
	(*CertAuth)(nil),                      // 3: minikms.v1.CertAuth
	(*CreateSessionResponse)(nil),         // 4: minikms.v1.CreateSessionResponse
	(*ValidateSessionRequest)(nil),        // 5: minikms.v1.ValidateSessionRequest
	(*ValidateSessionResponse)(nil),       // 6: minikms.v1.ValidateSessionResponse
	(*RevokeSessionRequest)(nil),          // 7: minikms.v1.RevokeSessionRequest
	(*RevokeSessionResponse)(nil),         // 8: minikms.v1.RevokeSessionResponse
	(*RevokeMemberSessionsRequest)(nil),   // 9: minikms.v1.RevokeMemberSessionsRequest
	(*RevokeMemberSessionsResponse)(nil),  // 10: minikms.v1.RevokeMemberSessionsResponse
	(*ListSessionsRequest)(nil),           // 11: minikms.v1.ListSessionsRequest
	(*ListSessionsResponse)(nil),          // 12: minikms.v1.ListSessionsResponse
	(*SessionInfo)(nil),                   // 13: minikms.v1.SessionInfo
	(*timestamppb.Timestamp)(nil),         // 14: google.protobuf.Timestamp
}
var file_api_proto_minikms_v1_session_proto_depIdxs = []int32{
	14, // 0: minikms.v1.IssueSessionChallengeResponse.expires_at:type_name -> google.protobuf.Timestamp
	3,  // 1: minikms.v1.CreateSessionRequest.cert_auth:type_name -> minikms.v1.CertAuth
	14, // 2: minikms.v1.CreateSessionResponse.expires_at:type_name -> google.protobuf.Timestamp
	14, // 3: minikms.v1.ValidateSessionResponse.expires_at:type_name -> google.protobuf.Timestamp
	13, // 4: minikms.v1.ListSessionsResponse.sessions:type_name -> minikms.v1.SessionInfo
	14, // 5: minikms.v1.SessionInfo.issued_at:type_name -> google.protobuf.Timestamp
	14, // 6: minikms.v1.SessionInfo.expires_at:type_name -> google.protobuf.Timestamp
	0,  // 7: minikms.v1.SessionService.IssueSessionChallenge:input_type -> minikms.v1.IssueSessionChallengeRequest
	2,  // 8: minikms.v1.SessionService.CreateSession:input_type -> minikms.v1.CreateSessionRequest
	5,  // 9: minikms.v1.SessionService.ValidateSession:input_type -> minikms.v1.ValidateSessionRequest
	7,  // 10: minikms.v1.SessionService.RevokeSession:input_type -> minikms.v1.RevokeSessionRequest
	9,  // 11: minikms.v1.SessionService.RevokeMemberSessions:input_type -> minikms.v1.RevokeMemberSessionsRequest
	11, // 12: minikms.v1.SessionService.ListSessions:input_type -> minikms.v1.ListSessionsRequest
	1,  // 13: minikms.v1.SessionService.IssueSessionChallenge:output_type -> minikms.v1.IssueSessionChallengeResponse
	4,  // 14: minikms.v1.SessionService.CreateSession:output_type -> minikms.v1.CreateSessionResponse
	6,  // 15: minikms.v1.SessionService.ValidateSession:output_type -> minikms.v1.ValidateSessionResponse
	8,  // 16: minikms.v1.SessionService.RevokeSession:output_type -> minikms.v1.RevokeSessionResponse
	10, // 17: minikms.v1.SessionService.RevokeMemberSessions:output_type -> minikms.v1.RevokeMemberSessionsResponse
	12, // 18: minikms.v1.SessionService.ListSessions:output_type -> minikms.v1.ListSessionsResponse
	13, // [13:19] is the sub-list for method output_type
	7,  // [7:13] is the sub-list for method input_type
	7,  // [7:7] is the sub-list for extension type_name
	7,  // [7:7] is the sub-list for extension extendee
	0,  // [0:7] is the sub-list for field type_name
}

func init() { file_api_proto_minikms_v1_session_proto_init() }
func file_api_proto_minikms_v1_session_proto_init() {
	if File_api_proto_minikms_v1_session_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_minikms_v1_session_proto_rawDesc), len(file_api_proto_minikms_v1_session_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   14,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_minikms_v1_session_proto_goTypes,
		DependencyIndexes: file_api_proto_minikms_v1_session_proto_depIdxs,
		MessageInfos:      file_api_proto_minikms_v1_session_proto_msgTypes,
	}.Build()
	File_api_proto_minikms_v1_session_proto = out.File
	file_api_proto_minikms_v1_session_proto_goTypes = nil
	file_api_proto_minikms_v1_session_proto_depIdxs = nil
}
