// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.11
// 	protoc        v6.33.4
// source: api/proto/minikms/v1/vault.proto

package minikmsv1

import (
	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

type VaultWriteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ScopeId       string                 `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`       // app_id
	EntryType     string                 `protobuf:"bytes,3,opt,name=entry_type,json=entryType,proto3" json:"entry_type,omitempty"` // "env", "secret", "gpg"
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	EnvTypeId     string                 `protobuf:"bytes,5,opt,name=env_type_id,json=envTypeId,proto3" json:"env_type_id,omitempty"` // for env/secret scoping
	Value         []byte                 `protobuf:"bytes,6,opt,name=value,proto3" json:"value,omitempty"`                            // RSA/Hybrid encrypted blob (Layer 1 output)
	CreatedBy     string                 `protobuf:"bytes,7,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`   // member_id
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultWriteRequest) Reset() {
	*x = VaultWriteRequest{}
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultWriteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultWriteRequest) ProtoMessage() {}

func (x *VaultWriteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultWriteRequest.ProtoReflect.Descriptor instead.
func (*VaultWriteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_vault_proto_rawDescGZIP(), []int{0}
}

func (x *VaultWriteRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *VaultWriteRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *VaultWriteRequest) GetEntryType() string {
	if x != nil {
		return x.EntryType
	}
	return ""
}

func (x *VaultWriteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VaultWriteRequest) GetEnvTypeId() string {
	if x != nil {
		return x.EnvTypeId
	}
	return ""
}

func (x *VaultWriteRequest) GetValue() []byte {
	if x != nil {
		return x.Value
	}
	return nil
}

func (x *VaultWriteRequest) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

type VaultWriteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Id            string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	Version       int32                  `protobuf:"varint,2,opt,name=version,proto3" json:"version,omitempty"`
	KeyVersionId  string                 `protobuf:"bytes,3,opt,name=key_version_id,json=keyVersionId,proto3" json:"key_version_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultWriteResponse) Reset() {
	*x = VaultWriteResponse{}
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultWriteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultWriteResponse) ProtoMessage() {}

func (x *VaultWriteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultWriteResponse.ProtoReflect.Descriptor instead.
func (*VaultWriteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_vault_proto_rawDescGZIP(), []int{1}
}

func (x *VaultWriteResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VaultWriteResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VaultWriteResponse) GetKeyVersionId() string {
	if x != nil {
		return x.KeyVersionId
	}
	return ""
}

type VaultReadRequest struct {
	state     protoimpl.MessageState `protogen:"open.v1"`
	OrgId     string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ScopeId   string                 `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	EntryType string                 `protobuf:"bytes,3,opt,name=entry_type,json=entryType,proto3" json:"entry_type,omitempty"`
	Key       string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	EnvTypeId string                 `protobuf:"bytes,5,opt,name=env_type_id,json=envTypeId,proto3" json:"env_type_id,omitempty"`
	// If true, return the KMS-unwrapped ECIES blob for client-side decryption (BYOK).
	// If false (managed), server performs full decryption.
	ClientSideDecrypt bool `protobuf:"varint,6,opt,name=client_side_decrypt,json=clientSideDecrypt,proto3" json:"client_side_decrypt,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VaultReadRequest) Reset() {
	*x = VaultReadRequest{}
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultReadRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultReadRequest) ProtoMessage() {}

func (x *VaultReadRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultReadRequest.ProtoReflect.Descriptor instead.
func (*VaultReadRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_vault_proto_rawDescGZIP(), []int{2}
}

func (x *VaultReadRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *VaultReadRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *VaultReadRequest) GetEntryType() string {
	if x != nil {
		return x.EntryType
	}
	return ""
}

func (x *VaultReadRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VaultReadRequest) GetEnvTypeId() string {
	if x != nil {
		return x.EnvTypeId
	}
	return ""
}

func (x *VaultReadRequest) GetClientSideDecrypt() bool {
	if x != nil {
		return x.ClientSideDecrypt
	}
	return false
}

type VaultReadResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Id             string                 `protobuf:"bytes,1,opt,name=id,proto3" json:"id,omitempty"`
	OrgId          string                 `protobuf:"bytes,2,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ScopeId        string                 `protobuf:"bytes,3,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	EntryType      string                 `protobuf:"bytes,4,opt,name=entry_type,json=entryType,proto3" json:"entry_type,omitempty"`
	Key            string                 `protobuf:"bytes,5,opt,name=key,proto3" json:"key,omitempty"`
	EnvTypeId      string                 `protobuf:"bytes,6,opt,name=env_type_id,json=envTypeId,proto3" json:"env_type_id,omitempty"`
	EncryptedValue []byte                 `protobuf:"bytes,7,opt,name=encrypted_value,json=encryptedValue,proto3" json:"encrypted_value,omitempty"` // Depends on client_side_decrypt:
	// true: ECIES blob (Layer 2 output) for client-side ECIES+RSA decrypt
	// false: RSA/Hybrid blob (Layer 1 output) for client RSA decrypt only
	KeyVersionId string                 `protobuf:"bytes,8,opt,name=key_version_id,json=keyVersionId,proto3" json:"key_version_id,omitempty"`
	Version      int32                  `protobuf:"varint,9,opt,name=version,proto3" json:"version,omitempty"`
	CreatedAt    *timestamppb.Timestamp `protobuf:"bytes,10,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy    string                 `protobuf:"bytes,11,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	// For BYOK client-side decrypt: includes the member's Org CA wrap data
	EciesEphemeralPub      []byte `protobuf:"bytes,12,opt,name=ecies_ephemeral_pub,json=eciesEphemeralPub,proto3" json:"ecies_ephemeral_pub,omitempty"`                  // from the ECIES encryption
	MemberWrapEphemeralPub []byte `protobuf:"bytes,13,opt,name=member_wrap_ephemeral_pub,json=memberWrapEphemeralPub,proto3" json:"member_wrap_ephemeral_pub,omitempty"` // from org_ca_wraps
	MemberWrappedOrgcaKey  []byte `protobuf:"bytes,14,opt,name=member_wrapped_orgca_key,json=memberWrappedOrgcaKey,proto3" json:"member_wrapped_orgca_key,omitempty"`    // from org_ca_wraps
	unknownFields          protoimpl.UnknownFields
	sizeCache              protoimpl.SizeCache
}

func (x *VaultReadResponse) Reset() {
	*x = VaultReadResponse{}
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultReadResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultReadResponse) ProtoMessage() {}

func (x *VaultReadResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultReadResponse.ProtoReflect.Descriptor instead.
func (*VaultReadResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_vault_proto_rawDescGZIP(), []int{3}
}

func (x *VaultReadResponse) GetId() string {
	if x != nil {
		return x.Id
	}
	return ""
}

func (x *VaultReadResponse) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *VaultReadResponse) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *VaultReadResponse) GetEntryType() string {
	if x != nil {
		return x.EntryType
	}
	return ""
}

func (x *VaultReadResponse) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VaultReadResponse) GetEnvTypeId() string {
	if x != nil {
		return x.EnvTypeId
	}
	return ""
}

func (x *VaultReadResponse) GetEncryptedValue() []byte {
	if x != nil {
		return x.EncryptedValue
	}
	return nil
}

func (x *VaultReadResponse) GetKeyVersionId() string {
	if x != nil {
		return x.KeyVersionId
	}
	return ""
}

func (x *VaultReadResponse) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VaultReadResponse) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VaultReadResponse) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *VaultReadResponse) GetEciesEphemeralPub() []byte {
	if x != nil {
		return x.EciesEphemeralPub
	}
	return nil
}

func (x *VaultReadResponse) GetMemberWrapEphemeralPub() []byte {
	if x != nil {
		return x.MemberWrapEphemeralPub
	}
	return nil
}

func (x *VaultReadResponse) GetMemberWrappedOrgcaKey() []byte {
	if x != nil {
		return x.MemberWrappedOrgcaKey
	}
	return nil
}

type VaultReadVersionRequest struct {
	state             protoimpl.MessageState `protogen:"open.v1"`
	OrgId             string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ScopeId           string                 `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	EntryType         string                 `protobuf:"bytes,3,opt,name=entry_type,json=entryType,proto3" json:"entry_type,omitempty"`
	Key               string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	EnvTypeId         string                 `protobuf:"bytes,5,opt,name=env_type_id,json=envTypeId,proto3" json:"env_type_id,omitempty"`
	Version           int32                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"`
	ClientSideDecrypt bool                   `protobuf:"varint,7,opt,name=client_side_decrypt,json=clientSideDecrypt,proto3" json:"client_side_decrypt,omitempty"`
	unknownFields     protoimpl.UnknownFields
	sizeCache         protoimpl.SizeCache
}

func (x *VaultReadVersionRequest) Reset() {
	*x = VaultReadVersionRequest{}
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[4]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultReadVersionRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultReadVersionRequest) ProtoMessage() {}

func (x *VaultReadVersionRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[4]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultReadVersionRequest.ProtoReflect.Descriptor instead.
func (*VaultReadVersionRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_vault_proto_rawDescGZIP(), []int{4}
}

func (x *VaultReadVersionRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *VaultReadVersionRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *VaultReadVersionRequest) GetEntryType() string {
	if x != nil {
		return x.EntryType
	}
	return ""
}

func (x *VaultReadVersionRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VaultReadVersionRequest) GetEnvTypeId() string {
	if x != nil {
		return x.EnvTypeId
	}
	return ""
}

func (x *VaultReadVersionRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VaultReadVersionRequest) GetClientSideDecrypt() bool {
	if x != nil {
		return x.ClientSideDecrypt
	}
	return false
}

type VaultDeleteRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ScopeId       string                 `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	EntryType     string                 `protobuf:"bytes,3,opt,name=entry_type,json=entryType,proto3" json:"entry_type,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	EnvTypeId     string                 `protobuf:"bytes,5,opt,name=env_type_id,json=envTypeId,proto3" json:"env_type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultDeleteRequest) Reset() {
	*x = VaultDeleteRequest{}
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[5]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultDeleteRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultDeleteRequest) ProtoMessage() {}

func (x *VaultDeleteRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[5]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultDeleteRequest.ProtoReflect.Descriptor instead.
func (*VaultDeleteRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_vault_proto_rawDescGZIP(), []int{5}
}

func (x *VaultDeleteRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *VaultDeleteRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *VaultDeleteRequest) GetEntryType() string {
	if x != nil {
		return x.EntryType
	}
	return ""
}

func (x *VaultDeleteRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VaultDeleteRequest) GetEnvTypeId() string {
	if x != nil {
		return x.EnvTypeId
	}
	return ""
}

type VaultDeleteResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Success       bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultDeleteResponse) Reset() {
	*x = VaultDeleteResponse{}
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[6]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultDeleteResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultDeleteResponse) ProtoMessage() {}

func (x *VaultDeleteResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[6]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultDeleteResponse.ProtoReflect.Descriptor instead.
func (*VaultDeleteResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_vault_proto_rawDescGZIP(), []int{6}
}

func (x *VaultDeleteResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

type VaultDestroyRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ScopeId       string                 `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	EntryType     string                 `protobuf:"bytes,3,opt,name=entry_type,json=entryType,proto3" json:"entry_type,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	EnvTypeId     string                 `protobuf:"bytes,5,opt,name=env_type_id,json=envTypeId,proto3" json:"env_type_id,omitempty"`
	Version       int32                  `protobuf:"varint,6,opt,name=version,proto3" json:"version,omitempty"` // 0 = destroy all versions
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultDestroyRequest) Reset() {
	*x = VaultDestroyRequest{}
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[7]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultDestroyRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultDestroyRequest) ProtoMessage() {}

func (x *VaultDestroyRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[7]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultDestroyRequest.ProtoReflect.Descriptor instead.
func (*VaultDestroyRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_vault_proto_rawDescGZIP(), []int{7}
}

func (x *VaultDestroyRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *VaultDestroyRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *VaultDestroyRequest) GetEntryType() string {
	if x != nil {
		return x.EntryType
	}
	return ""
}

func (x *VaultDestroyRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VaultDestroyRequest) GetEnvTypeId() string {
	if x != nil {
		return x.EnvTypeId
	}
	return ""
}

func (x *VaultDestroyRequest) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

type VaultDestroyResponse struct {
	state          protoimpl.MessageState `protogen:"open.v1"`
	Success        bool                   `protobuf:"varint,1,opt,name=success,proto3" json:"success,omitempty"`
	DestroyedCount int32                  `protobuf:"varint,2,opt,name=destroyed_count,json=destroyedCount,proto3" json:"destroyed_count,omitempty"`
	unknownFields  protoimpl.UnknownFields
	sizeCache      protoimpl.SizeCache
}

func (x *VaultDestroyResponse) Reset() {
	*x = VaultDestroyResponse{}
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[8]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultDestroyResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultDestroyResponse) ProtoMessage() {}

func (x *VaultDestroyResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[8]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultDestroyResponse.ProtoReflect.Descriptor instead.
func (*VaultDestroyResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_vault_proto_rawDescGZIP(), []int{8}
}

func (x *VaultDestroyResponse) GetSuccess() bool {
	if x != nil {
		return x.Success
	}
	return false
}

func (x *VaultDestroyResponse) GetDestroyedCount() int32 {
	if x != nil {
		return x.DestroyedCount
	}
	return 0
}

type VaultListRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ScopeId       string                 `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	EntryType     string                 `protobuf:"bytes,3,opt,name=entry_type,json=entryType,proto3" json:"entry_type,omitempty"`
	EnvTypeId     string                 `protobuf:"bytes,4,opt,name=env_type_id,json=envTypeId,proto3" json:"env_type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultListRequest) Reset() {
	*x = VaultListRequest{}
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[9]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultListRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultListRequest) ProtoMessage() {}

func (x *VaultListRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[9]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultListRequest.ProtoReflect.Descriptor instead.
func (*VaultListRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_vault_proto_rawDescGZIP(), []int{9}
}

func (x *VaultListRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *VaultListRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *VaultListRequest) GetEntryType() string {
	if x != nil {
		return x.EntryType
	}
	return ""
}

func (x *VaultListRequest) GetEnvTypeId() string {
	if x != nil {
		return x.EnvTypeId
	}
	return ""
}

type VaultListResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Entries       []*VaultListEntry      `protobuf:"bytes,1,rep,name=entries,proto3" json:"entries,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultListResponse) Reset() {
	*x = VaultListResponse{}
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[10]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultListResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultListResponse) ProtoMessage() {}

func (x *VaultListResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[10]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultListResponse.ProtoReflect.Descriptor instead.
func (*VaultListResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_vault_proto_rawDescGZIP(), []int{10}
}

func (x *VaultListResponse) GetEntries() []*VaultListEntry {
	if x != nil {
		return x.Entries
	}
	return nil
}

type VaultListEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Key           string                 `protobuf:"bytes,1,opt,name=key,proto3" json:"key,omitempty"`
	LatestVersion int32                  `protobuf:"varint,2,opt,name=latest_version,json=latestVersion,proto3" json:"latest_version,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	UpdatedAt     *timestamppb.Timestamp `protobuf:"bytes,4,opt,name=updated_at,json=updatedAt,proto3" json:"updated_at,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultListEntry) Reset() {
	*x = VaultListEntry{}
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[11]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultListEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultListEntry) ProtoMessage() {}

func (x *VaultListEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[11]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultListEntry.ProtoReflect.Descriptor instead.
func (*VaultListEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_vault_proto_rawDescGZIP(), []int{11}
}

func (x *VaultListEntry) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VaultListEntry) GetLatestVersion() int32 {
	if x != nil {
		return x.LatestVersion
	}
	return 0
}

func (x *VaultListEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VaultListEntry) GetUpdatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.UpdatedAt
	}
	return nil
}

type VaultHistoryRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	OrgId         string                 `protobuf:"bytes,1,opt,name=org_id,json=orgId,proto3" json:"org_id,omitempty"`
	ScopeId       string                 `protobuf:"bytes,2,opt,name=scope_id,json=scopeId,proto3" json:"scope_id,omitempty"`
	EntryType     string                 `protobuf:"bytes,3,opt,name=entry_type,json=entryType,proto3" json:"entry_type,omitempty"`
	Key           string                 `protobuf:"bytes,4,opt,name=key,proto3" json:"key,omitempty"`
	EnvTypeId     string                 `protobuf:"bytes,5,opt,name=env_type_id,json=envTypeId,proto3" json:"env_type_id,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultHistoryRequest) Reset() {
	*x = VaultHistoryRequest{}
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[12]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultHistoryRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultHistoryRequest) ProtoMessage() {}

func (x *VaultHistoryRequest) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[12]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultHistoryRequest.ProtoReflect.Descriptor instead.
func (*VaultHistoryRequest) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_vault_proto_rawDescGZIP(), []int{12}
}

func (x *VaultHistoryRequest) GetOrgId() string {
	if x != nil {
		return x.OrgId
	}
	return ""
}

func (x *VaultHistoryRequest) GetScopeId() string {
	if x != nil {
		return x.ScopeId
	}
	return ""
}

func (x *VaultHistoryRequest) GetEntryType() string {
	if x != nil {
		return x.EntryType
	}
	return ""
}

func (x *VaultHistoryRequest) GetKey() string {
	if x != nil {
		return x.Key
	}
	return ""
}

func (x *VaultHistoryRequest) GetEnvTypeId() string {
	if x != nil {
		return x.EnvTypeId
	}
	return ""
}

type VaultHistoryResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Versions      []*VaultVersionEntry   `protobuf:"bytes,1,rep,name=versions,proto3" json:"versions,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultHistoryResponse) Reset() {
	*x = VaultHistoryResponse{}
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[13]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultHistoryResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultHistoryResponse) ProtoMessage() {}

func (x *VaultHistoryResponse) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[13]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultHistoryResponse.ProtoReflect.Descriptor instead.
func (*VaultHistoryResponse) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_vault_proto_rawDescGZIP(), []int{13}
}

func (x *VaultHistoryResponse) GetVersions() []*VaultVersionEntry {
	if x != nil {
		return x.Versions
	}
	return nil
}

type VaultVersionEntry struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Version       int32                  `protobuf:"varint,1,opt,name=version,proto3" json:"version,omitempty"`
	KeyVersionId  string                 `protobuf:"bytes,2,opt,name=key_version_id,json=keyVersionId,proto3" json:"key_version_id,omitempty"`
	CreatedAt     *timestamppb.Timestamp `protobuf:"bytes,3,opt,name=created_at,json=createdAt,proto3" json:"created_at,omitempty"`
	CreatedBy     string                 `protobuf:"bytes,4,opt,name=created_by,json=createdBy,proto3" json:"created_by,omitempty"`
	Deleted       bool                   `protobuf:"varint,5,opt,name=deleted,proto3" json:"deleted,omitempty"`
	Destroyed     bool                   `protobuf:"varint,6,opt,name=destroyed,proto3" json:"destroyed,omitempty"`
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *VaultVersionEntry) Reset() {
	*x = VaultVersionEntry{}
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[14]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *VaultVersionEntry) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*VaultVersionEntry) ProtoMessage() {}

func (x *VaultVersionEntry) ProtoReflect() protoreflect.Message {
	mi := &file_api_proto_minikms_v1_vault_proto_msgTypes[14]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use VaultVersionEntry.ProtoReflect.Descriptor instead.
func (*VaultVersionEntry) Descriptor() ([]byte, []int) {
	return file_api_proto_minikms_v1_vault_proto_rawDescGZIP(), []int{14}
}

func (x *VaultVersionEntry) GetVersion() int32 {
	if x != nil {
		return x.Version
	}
	return 0
}

func (x *VaultVersionEntry) GetKeyVersionId() string {
	if x != nil {
		return x.KeyVersionId
	}
	return ""
}

func (x *VaultVersionEntry) GetCreatedAt() *timestamppb.Timestamp {
	if x != nil {
		return x.CreatedAt
	}
	return nil
}

func (x *VaultVersionEntry) GetCreatedBy() string {
	if x != nil {
		return x.CreatedBy
	}
	return ""
}

func (x *VaultVersionEntry) GetDeleted() bool {
	if x != nil {
		return x.Deleted
	}
	return false
}

func (x *VaultVersionEntry) GetDestroyed() bool {
	if x != nil {
		return x.Destroyed
	}
	return false
}

var File_api_proto_minikms_v1_vault_proto protoreflect.FileDescriptor

const file_api_proto_minikms_v1_vault_proto_rawDesc = "" +
	"\n" +
	" api/proto/minikms/v1/vault.proto\x12\n" +
	"minikms.v1\x1a\x1fgoogle/protobuf/timestamp.proto\"\xcb\x01\n" +
	"\x11VaultWriteRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\x12\x1d\n" +
	"\n" +
	"entry_type\x18\x03 \x01(\tR\tentryType\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x1e\n" +
	"\venv_type_id\x18\x05 \x01(\tR\tenvTypeId\x12\x14\n" +
	"\x05value\x18\x06 \x01(\fR\x05value\x12\x1d\n" +
	"\n" +
	"created_by\x18\a \x01(\tR\tcreatedBy\"d\n" +
	"\x12VaultWriteResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x18\n" +
	"\aversion\x18\x02 \x01(\x05R\aversion\x12$\n" +
	"\x0ekey_version_id\x18\x03 \x01(\tR\fkeyVersionId\"\xc5\x01\n" +
	"\x10VaultReadRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\x12\x1d\n" +
	"\n" +
	"entry_type\x18\x03 \x01(\tR\tentryType\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x1e\n" +
	"\venv_type_id\x18\x05 \x01(\tR\tenvTypeId\x12.\n" +
	"\x13client_side_decrypt\x18\x06 \x01(\bR\x11clientSideDecrypt\"\x8d\x04\n" +
	"\x11VaultReadResponse\x12\x0e\n" +
	"\x02id\x18\x01 \x01(\tR\x02id\x12\x15\n" +
	"\x06org_id\x18\x02 \x01(\tR\x05orgId\x12\x19\n" +
	"\bscope_id\x18\x03 \x01(\tR\ascopeId\x12\x1d\n" +
	"\n" +
	"entry_type\x18\x04 \x01(\tR\tentryType\x12\x10\n" +
	"\x03key\x18\x05 \x01(\tR\x03key\x12\x1e\n" +
	"\venv_type_id\x18\x06 \x01(\tR\tenvTypeId\x12'\n" +
	"\x0fencrypted_value\x18\a \x01(\fR\x0eencryptedValue\x12$\n" +
	"\x0ekey_version_id\x18\b \x01(\tR\fkeyVersionId\x12\x18\n" +
	"\aversion\x18\t \x01(\x05R\aversion\x129\n" +
	"\n" +
	"created_at\x18\n" +
	" \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\v \x01(\tR\tcreatedBy\x12.\n" +
	"\x13ecies_ephemeral_pub\x18\f \x01(\fR\x11eciesEphemeralPub\x129\n" +
	"\x19member_wrap_ephemeral_pub\x18\r \x01(\fR\x16memberWrapEphemeralPub\x127\n" +
	"\x18member_wrapped_orgca_key\x18\x0e \x01(\fR\x15memberWrappedOrgcaKey\"\xe6\x01\n" +
	"\x17VaultReadVersionRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\x12\x1d\n" +
	"\n" +
	"entry_type\x18\x03 \x01(\tR\tentryType\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x1e\n" +
	"\venv_type_id\x18\x05 \x01(\tR\tenvTypeId\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversion\x12.\n" +
	"\x13client_side_decrypt\x18\a \x01(\bR\x11clientSideDecrypt\"\x97\x01\n" +
	"\x12VaultDeleteRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\x12\x1d\n" +
	"\n" +
	"entry_type\x18\x03 \x01(\tR\tentryType\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x1e\n" +
	"\venv_type_id\x18\x05 \x01(\tR\tenvTypeId\"/\n" +
	"\x13VaultDeleteResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\"\xb2\x01\n" +
	"\x13VaultDestroyRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\x12\x1d\n" +
	"\n" +
	"entry_type\x18\x03 \x01(\tR\tentryType\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x1e\n" +
	"\venv_type_id\x18\x05 \x01(\tR\tenvTypeId\x12\x18\n" +
	"\aversion\x18\x06 \x01(\x05R\aversion\"Y\n" +
	"\x14VaultDestroyResponse\x12\x18\n" +
	"\asuccess\x18\x01 \x01(\bR\asuccess\x12'\n" +
	"\x0fdestroyed_count\x18\x02 \x01(\x05R\x0edestroyedCount\"\x83\x01\n" +
	"\x10VaultListRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\x12\x1d\n" +
	"\n" +
	"entry_type\x18\x03 \x01(\tR\tentryType\x12\x1e\n" +
	"\venv_type_id\x18\x04 \x01(\tR\tenvTypeId\"I\n" +
	"\x11VaultListResponse\x124\n" +
	"\aentries\x18\x01 \x03(\v2\x1a.minikms.v1.VaultListEntryR\aentries\"\xbf\x01\n" +
	"\x0eVaultListEntry\x12\x10\n" +
	"\x03key\x18\x01 \x01(\tR\x03key\x12%\n" +
	"\x0elatest_version\x18\x02 \x01(\x05R\rlatestVersion\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x129\n" +
	"\n" +
	"updated_at\x18\x04 \x01(\v2\x1a.google.protobuf.TimestampR\tupdatedAt\"\x98\x01\n" +
	"\x13VaultHistoryRequest\x12\x15\n" +
	"\x06org_id\x18\x01 \x01(\tR\x05orgId\x12\x19\n" +
	"\bscope_id\x18\x02 \x01(\tR\ascopeId\x12\x1d\n" +
	"\n" +
	"entry_type\x18\x03 \x01(\tR\tentryType\x12\x10\n" +
	"\x03key\x18\x04 \x01(\tR\x03key\x12\x1e\n" +
	"\venv_type_id\x18\x05 \x01(\tR\tenvTypeId\"Q\n" +
	"\x14VaultHistoryResponse\x129\n" +
	"\bversions\x18\x01 \x03(\v2\x1d.minikms.v1.VaultVersionEntryR\bversions\"\xe5\x01\n" +
	"\x11VaultVersionEntry\x12\x18\n" +
	"\aversion\x18\x01 \x01(\x05R\aversion\x12$\n" +
	"\x0ekey_version_id\x18\x02 \x01(\tR\fkeyVersionId\x129\n" +
	"\n" +
	"created_at\x18\x03 \x01(\v2\x1a.google.protobuf.TimestampR\tcreatedAt\x12\x1d\n" +
	"\n" +
	"created_by\x18\x04 \x01(\tR\tcreatedBy\x12\x18\n" +
	"\adeleted\x18\x05 \x01(\bR\adeleted\x12\x1c\n" +
	"\tdestroyed\x18\x06 \x01(\bR\tdestroyed2\x9a\x04\n" +
	"\fVaultService\x12F\n" +
	"\x05Write\x12\x1d.minikms.v1.VaultWriteRequest\x1a\x1e.minikms.v1.VaultWriteResponse\x12C\n" +
	"\x04Read\x12\x1c.minikms.v1.VaultReadRequest\x1a\x1d.minikms.v1.VaultReadResponse\x12Q\n" +
	"\vReadVersion\x12#.minikms.v1.VaultReadVersionRequest\x1a\x1d.minikms.v1.VaultReadResponse\x12I\n" +
	"\x06Delete\x12\x1e.minikms.v1.VaultDeleteRequest\x1a\x1f.minikms.v1.VaultDeleteResponse\x12L\n" +
	"\aDestroy\x12\x1f.minikms.v1.VaultDestroyRequest\x1a .minikms.v1.VaultDestroyResponse\x12C\n" +
	"\x04List\x12\x1c.minikms.v1.VaultListRequest\x1a\x1d.minikms.v1.VaultListResponse\x12L\n" +
	"\aHistory\x12\x1f.minikms.v1.VaultHistoryRequest\x1a .minikms.v1.VaultHistoryResponseB;Z9github.com/envsync/minikms/api/proto/minikms/v1;minikmsv1b\x06proto3"

var (
	file_api_proto_minikms_v1_vault_proto_rawDescOnce sync.Once
	file_api_proto_minikms_v1_vault_proto_rawDescData []byte
)

func file_api_proto_minikms_v1_vault_proto_rawDescGZIP() []byte {
	file_api_proto_minikms_v1_vault_proto_rawDescOnce.Do(func() {
		file_api_proto_minikms_v1_vault_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_api_proto_minikms_v1_vault_proto_rawDesc), len(file_api_proto_minikms_v1_vault_proto_rawDesc)))
	})
	return file_api_proto_minikms_v1_vault_proto_rawDescData
}

var file_api_proto_minikms_v1_vault_proto_msgTypes = make([]protoimpl.MessageInfo, 15)
var file_api_proto_minikms_v1_vault_proto_goTypes = []any{
	(*VaultWriteRequest)(nil),       // 0: minikms.v1.VaultWriteRequest
	(*VaultWriteResponse)(nil),      // 1: minikms.v1.VaultWriteResponse
	(*VaultReadRequest)(nil),        // 2: minikms.v1.VaultReadRequest
	(*VaultReadResponse)(nil),       // 3: minikms.v1.VaultReadResponse
	(*VaultReadVersionRequest)(nil), // 4: minikms.v1.VaultReadVersionRequest
	(*VaultDeleteRequest)(nil),      // 5: minikms.v1.VaultDeleteRequest
	(*VaultDeleteResponse)(nil),     // 6: minikms.v1.VaultDeleteResponse
	(*VaultDestroyRequest)(nil),     // 7: minikms.v1.VaultDestroyRequest
	(*VaultDestroyResponse)(nil),    // 8: minikms.v1.VaultDestroyResponse
	(*VaultListRequest)(nil),        // 9: minikms.v1.VaultListRequest
	(*VaultListResponse)(nil),       // 10: minikms.v1.VaultListResponse
	(*VaultListEntry)(nil),          // 11: minikms.v1.VaultListEntry
	(*VaultHistoryRequest)(nil),     // 12: minikms.v1.VaultHistoryRequest
	(*VaultHistoryResponse)(nil),    // 13: minikms.v1.VaultHistoryResponse
	(*VaultVersionEntry)(nil),       // 14: minikms.v1.VaultVersionEntry
	(*timestamppb.Timestamp)(nil),   // 15: google.protobuf.Timestamp
}
var file_api_proto_minikms_v1_vault_proto_depIdxs = []int32{
	15, // 0: minikms.v1.VaultReadResponse.created_at:type_name -> google.protobuf.Timestamp
	11, // 1: minikms.v1.VaultListResponse.entries:type_name -> minikms.v1.VaultListEntry
	15, // 2: minikms.v1.VaultListEntry.created_at:type_name -> google.protobuf.Timestamp
	15, // 3: minikms.v1.VaultListEntry.updated_at:type_name -> google.protobuf.Timestamp
	14, // 4: minikms.v1.VaultHistoryResponse.versions:type_name -> minikms.v1.VaultVersionEntry
	15, // 5: minikms.v1.VaultVersionEntry.created_at:type_name -> google.protobuf.Timestamp
	0,  // 6: minikms.v1.VaultService.Write:input_type -> minikms.v1.VaultWriteRequest
	2,  // 7: minikms.v1.VaultService.Read:input_type -> minikms.v1.VaultReadRequest
	4,  // 8: minikms.v1.VaultService.ReadVersion:input_type -> minikms.v1.VaultReadVersionRequest
	5,  // 9: minikms.v1.VaultService.Delete:input_type -> minikms.v1.VaultDeleteRequest
	7,  // 10: minikms.v1.VaultService.Destroy:input_type -> minikms.v1.VaultDestroyRequest
	9,  // 11: minikms.v1.VaultService.List:input_type -> minikms.v1.VaultListRequest
	12, // 12: minikms.v1.VaultService.History:input_type -> minikms.v1.VaultHistoryRequest
	1,  // 13: minikms.v1.VaultService.Write:output_type -> minikms.v1.VaultWriteResponse
	3,  // 14: minikms.v1.VaultService.Read:output_type -> minikms.v1.VaultReadResponse
	3,  // 15: minikms.v1.VaultService.ReadVersion:output_type -> minikms.v1.VaultReadResponse
	6,  // 16: minikms.v1.VaultService.Delete:output_type -> minikms.v1.VaultDeleteResponse
	8,  // 17: minikms.v1.VaultService.Destroy:output_type -> minikms.v1.VaultDestroyResponse
	10, // 18: minikms.v1.VaultService.List:output_type -> minikms.v1.VaultListResponse
	13, // 19: minikms.v1.VaultService.History:output_type -> minikms.v1.VaultHistoryResponse
	13, // [13:20] is the sub-list for method output_type
	6,  // [6:13] is the sub-list for method input_type
	6,  // [6:6] is the sub-list for extension type_name
	6,  // [6:6] is the sub-list for extension extendee
	0,  // [0:6] is the sub-list for field type_name
}

func init() { file_api_proto_minikms_v1_vault_proto_init() }
func file_api_proto_minikms_v1_vault_proto_init() {
	if File_api_proto_minikms_v1_vault_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_api_proto_minikms_v1_vault_proto_rawDesc), len(file_api_proto_minikms_v1_vault_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   15,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_api_proto_minikms_v1_vault_proto_goTypes,
		DependencyIndexes: file_api_proto_minikms_v1_vault_proto_depIdxs,
		MessageInfos:      file_api_proto_minikms_v1_vault_proto_msgTypes,
	}.Build()
	File_api_proto_minikms_v1_vault_proto = out.File
	file_api_proto_minikms_v1_vault_proto_goTypes = nil
	file_api_proto_minikms_v1_vault_proto_depIdxs = nil
}
