// Code generated by protoc-gen-go-grpc. DO NOT EDIT.
// versions:
// - protoc-gen-go-grpc v1.6.1
// - protoc             v6.33.4
// source: api/proto/minikms/v1/vault.proto

package minikmsv1

import (
	context "context"
	grpc "google.golang.org/grpc"
	codes "google.golang.org/grpc/codes"
	status "google.golang.org/grpc/status"
)

// This is a compile-time assertion to ensure that this generated file
// is compatible with the grpc package it is being compiled against.
// Requires gRPC-Go v1.64.0 or later.
const _ = grpc.SupportPackageIsVersion9

const (
	VaultService_Write_FullMethodName       = "/minikms.v1.VaultService/Write"
	VaultService_Read_FullMethodName        = "/minikms.v1.VaultService/Read"
	VaultService_ReadVersion_FullMethodName = "/minikms.v1.VaultService/ReadVersion"
	VaultService_Delete_FullMethodName      = "/minikms.v1.VaultService/Delete"
	VaultService_Destroy_FullMethodName     = "/minikms.v1.VaultService/Destroy"
	VaultService_List_FullMethodName        = "/minikms.v1.VaultService/List"
	VaultService_History_FullMethodName     = "/minikms.v1.VaultService/History"
)

// VaultServiceClient is the client API for VaultService service.
//
// For semantics around ctx use and closing/ending streaming RPCs, please refer to https://pkg.go.dev/google.golang.org/grpc/?tab=doc#ClientConn.NewStream.
//
// VaultService provides zero-trust secret storage, replacing HashiCorp Vault KV v2.
// All operations require a valid session token in gRPC metadata.
// Write operations create new versions (append-only).
// ECIES encryption happens inside Write; ECIES decryption inside Read.
type VaultServiceClient interface {
	// Write stores an encrypted value, creating a new version.
	Write(ctx context.Context, in *VaultWriteRequest, opts ...grpc.CallOption) (*VaultWriteResponse, error)
	// Read retrieves the latest version of a vault entry.
	Read(ctx context.Context, in *VaultReadRequest, opts ...grpc.CallOption) (*VaultReadResponse, error)
	// ReadVersion retrieves a specific version of a vault entry.
	ReadVersion(ctx context.Context, in *VaultReadVersionRequest, opts ...grpc.CallOption) (*VaultReadResponse, error)
	// Delete performs a soft delete (marks as deleted, recoverable).
	Delete(ctx context.Context, in *VaultDeleteRequest, opts ...grpc.CallOption) (*VaultDeleteResponse, error)
	// Destroy permanently deletes a vault entry (irrecoverable).
	Destroy(ctx context.Context, in *VaultDestroyRequest, opts ...grpc.CallOption) (*VaultDestroyResponse, error)
	// List returns all active keys within a scope.
	List(ctx context.Context, in *VaultListRequest, opts ...grpc.CallOption) (*VaultListResponse, error)
	// History returns the version history of a vault entry.
	History(ctx context.Context, in *VaultHistoryRequest, opts ...grpc.CallOption) (*VaultHistoryResponse, error)
}

type vaultServiceClient struct {
	cc grpc.ClientConnInterface
}

func NewVaultServiceClient(cc grpc.ClientConnInterface) VaultServiceClient {
	return &vaultServiceClient{cc}
}

func (c *vaultServiceClient) Write(ctx context.Context, in *VaultWriteRequest, opts ...grpc.CallOption) (*VaultWriteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VaultWriteResponse)
	err := c.cc.Invoke(ctx, VaultService_Write_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) Read(ctx context.Context, in *VaultReadRequest, opts ...grpc.CallOption) (*VaultReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VaultReadResponse)
	err := c.cc.Invoke(ctx, VaultService_Read_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) ReadVersion(ctx context.Context, in *VaultReadVersionRequest, opts ...grpc.CallOption) (*VaultReadResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VaultReadResponse)
	err := c.cc.Invoke(ctx, VaultService_ReadVersion_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) Delete(ctx context.Context, in *VaultDeleteRequest, opts ...grpc.CallOption) (*VaultDeleteResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VaultDeleteResponse)
	err := c.cc.Invoke(ctx, VaultService_Delete_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) Destroy(ctx context.Context, in *VaultDestroyRequest, opts ...grpc.CallOption) (*VaultDestroyResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VaultDestroyResponse)
	err := c.cc.Invoke(ctx, VaultService_Destroy_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) List(ctx context.Context, in *VaultListRequest, opts ...grpc.CallOption) (*VaultListResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VaultListResponse)
	err := c.cc.Invoke(ctx, VaultService_List_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

func (c *vaultServiceClient) History(ctx context.Context, in *VaultHistoryRequest, opts ...grpc.CallOption) (*VaultHistoryResponse, error) {
	cOpts := append([]grpc.CallOption{grpc.StaticMethod()}, opts...)
	out := new(VaultHistoryResponse)
	err := c.cc.Invoke(ctx, VaultService_History_FullMethodName, in, out, cOpts...)
	if err != nil {
		return nil, err
	}
	return out, nil
}

// VaultServiceServer is the server API for VaultService service.
// All implementations must embed UnimplementedVaultServiceServer
// for forward compatibility.
//
// VaultService provides zero-trust secret storage, replacing HashiCorp Vault KV v2.
// All operations require a valid session token in gRPC metadata.
// Write operations create new versions (append-only).
// ECIES encryption happens inside Write; ECIES decryption inside Read.
type VaultServiceServer interface {
	// Write stores an encrypted value, creating a new version.
	Write(context.Context, *VaultWriteRequest) (*VaultWriteResponse, error)
	// Read retrieves the latest version of a vault entry.
	Read(context.Context, *VaultReadRequest) (*VaultReadResponse, error)
	// ReadVersion retrieves a specific version of a vault entry.
	ReadVersion(context.Context, *VaultReadVersionRequest) (*VaultReadResponse, error)
	// Delete performs a soft delete (marks as deleted, recoverable).
	Delete(context.Context, *VaultDeleteRequest) (*VaultDeleteResponse, error)
	// Destroy permanently deletes a vault entry (irrecoverable).
	Destroy(context.Context, *VaultDestroyRequest) (*VaultDestroyResponse, error)
	// List returns all active keys within a scope.
	List(context.Context, *VaultListRequest) (*VaultListResponse, error)
	// History returns the version history of a vault entry.
	History(context.Context, *VaultHistoryRequest) (*VaultHistoryResponse, error)
	mustEmbedUnimplementedVaultServiceServer()
}

// UnimplementedVaultServiceServer must be embedded to have
// forward compatible implementations.
//
// NOTE: this should be embedded by value instead of pointer to avoid a nil
// pointer dereference when methods are called.
type UnimplementedVaultServiceServer struct{}

func (UnimplementedVaultServiceServer) Write(context.Context, *VaultWriteRequest) (*VaultWriteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Write not implemented")
}
func (UnimplementedVaultServiceServer) Read(context.Context, *VaultReadRequest) (*VaultReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Read not implemented")
}
func (UnimplementedVaultServiceServer) ReadVersion(context.Context, *VaultReadVersionRequest) (*VaultReadResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method ReadVersion not implemented")
}
func (UnimplementedVaultServiceServer) Delete(context.Context, *VaultDeleteRequest) (*VaultDeleteResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Delete not implemented")
}
func (UnimplementedVaultServiceServer) Destroy(context.Context, *VaultDestroyRequest) (*VaultDestroyResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method Destroy not implemented")
}
func (UnimplementedVaultServiceServer) List(context.Context, *VaultListRequest) (*VaultListResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method List not implemented")
}
func (UnimplementedVaultServiceServer) History(context.Context, *VaultHistoryRequest) (*VaultHistoryResponse, error) {
	return nil, status.Error(codes.Unimplemented, "method History not implemented")
}
func (UnimplementedVaultServiceServer) mustEmbedUnimplementedVaultServiceServer() {}
func (UnimplementedVaultServiceServer) testEmbeddedByValue()                      {}

// UnsafeVaultServiceServer may be embedded to opt out of forward compatibility for this service.
// Use of this interface is not recommended, as added methods to VaultServiceServer will
// result in compilation errors.
type UnsafeVaultServiceServer interface {
	mustEmbedUnimplementedVaultServiceServer()
}

func RegisterVaultServiceServer(s grpc.ServiceRegistrar, srv VaultServiceServer) {
	// If the following call panics, it indicates UnimplementedVaultServiceServer was
	// embedded by pointer and is nil.  This will cause panics if an
	// unimplemented method is ever invoked, so we test this at initialization
	// time to prevent it from happening at runtime later due to I/O.
	if t, ok := srv.(interface{ testEmbeddedByValue() }); ok {
		t.testEmbeddedByValue()
	}
	s.RegisterService(&VaultService_ServiceDesc, srv)
}

func _VaultService_Write_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VaultWriteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).Write(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_Write_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).Write(ctx, req.(*VaultWriteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_Read_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VaultReadRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).Read(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_Read_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).Read(ctx, req.(*VaultReadRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_ReadVersion_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VaultReadVersionRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).ReadVersion(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_ReadVersion_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).ReadVersion(ctx, req.(*VaultReadVersionRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_Delete_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VaultDeleteRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).Delete(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_Delete_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).Delete(ctx, req.(*VaultDeleteRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_Destroy_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VaultDestroyRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).Destroy(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_Destroy_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).Destroy(ctx, req.(*VaultDestroyRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_List_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VaultListRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).List(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_List_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).List(ctx, req.(*VaultListRequest))
	}
	return interceptor(ctx, in, info, handler)
}

func _VaultService_History_Handler(srv interface{}, ctx context.Context, dec func(interface{}) error, interceptor grpc.UnaryServerInterceptor) (interface{}, error) {
	in := new(VaultHistoryRequest)
	if err := dec(in); err != nil {
		return nil, err
	}
	if interceptor == nil {
		return srv.(VaultServiceServer).History(ctx, in)
	}
	info := &grpc.UnaryServerInfo{
		Server:     srv,
		FullMethod: VaultService_History_FullMethodName,
	}
	handler := func(ctx context.Context, req interface{}) (interface{}, error) {
		return srv.(VaultServiceServer).History(ctx, req.(*VaultHistoryRequest))
	}
	return interceptor(ctx, in, info, handler)
}

// VaultService_ServiceDesc is the grpc.ServiceDesc for VaultService service.
// It's only intended for direct use with grpc.RegisterService,
// and not to be introspected or modified (even as a copy)
var VaultService_ServiceDesc = grpc.ServiceDesc{
	ServiceName: "minikms.v1.VaultService",
	HandlerType: (*VaultServiceServer)(nil),
	Methods: []grpc.MethodDesc{
		{
			MethodName: "Write",
			Handler:    _VaultService_Write_Handler,
		},
		{
			MethodName: "Read",
			Handler:    _VaultService_Read_Handler,
		},
		{
			MethodName: "ReadVersion",
			Handler:    _VaultService_ReadVersion_Handler,
		},
		{
			MethodName: "Delete",
			Handler:    _VaultService_Delete_Handler,
		},
		{
			MethodName: "Destroy",
			Handler:    _VaultService_Destroy_Handler,
		},
		{
			MethodName: "List",
			Handler:    _VaultService_List_Handler,
		},
		{
			MethodName: "History",
			Handler:    _VaultService_History_Handler,
		},
	},
	Streams:  []grpc.StreamDesc{},
	Metadata: "api/proto/minikms/v1/vault.proto",
}
